### ISSUE TITLE
Erro ao tentar emitir NFe no ambiente de homologação.

### ISSUE THREAD

**Issue by rodriguesraphael** [Trust-Code/odoo-brasil#1]
Ao tentar emitir uma nota fiscal no ambiente de homologação o Odoo retorna o seguinte erro.

Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo/odoo-brasil/br_nfe/models/invoice_eletronic.py", line 490, in action_send_eletronic_invoice
    nfe_values = self._prepare_eletronic_invoice_values()
  File "/home/odoo/odoo/odoo-brasil/br_nfe/models/invoice_eletronic.py", line 340, in _prepare_eletronic_invoice_values
    self._prepare_eletronic_invoice_item(item, self))
  File "/home/odoo/odoo/odoo-brasil/br_nfe/models/invoice_eletronic.py", line 159, in _prepare_eletronic_invoice_item
    res = super(InvoiceEletronic, self)._prepare_eletronic_invoice_item(
AttributeError: 'super' object has no attribute '_prepare_eletronic_invoice_item'

**Comment by danimaribeiro** [comment]
Fixed https://github.com/Trust-Code/odoo-brasil/commit/7cb11fabf5e482395e199112757ca17d741f2994
