### ISSUE TITLE
Odoo Versão 12 não cria um banco de dados novo

### ISSUE THREAD

**Issue by gilsonlima10** [Trust-Code/odoo-brasil#1102]
em determinado ponto da criação apresenta o seguinte erro:
2021-06-11 09:35:50,204 27171 ERROR 123 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/res_country.py", line 104, in _check_address_format
    record.address_format % {i: 1 for i in address_fields}
KeyError: 'city_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/models.py", line 1128, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_country.py", line 106, in _check_address_format
    raise UserError(_('The layout contains an invalid format key'))
odoo.exceptions.UserError: ('The layout contains an invalid format key', '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo/odoo/odoo/models.py", line 3881, in _load_records
    data['record']._load_records_write(data['values'])
  File "/opt/odoo/odoo/odoo/models.py", line 3819, in _load_records_write
    self.write(values)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_country.py", line 91, in write
    return super(Country, self).write(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3364, in write
    self._write(store_vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3500, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 1132, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nThe layout contains an invalid format key\n', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 e segue......

**Comment by fabioluna** [comment]
Para sabermos realmente o que aconteceu neste caso, precisamos do log completo do erro. Consegue enviar por favor?

**Comment by gilsonlima10** [comment]
Segue ...
2021-06-17 00:38:36,710 19759 INFO None odoo.service.db: Create database `teste`. 
2021-06-17 00:38:50,725 19759 INFO teste odoo.modules.loading: loading 1 modules... 
2021-06-17 00:38:50,909 19759 INFO teste odoo.modules.registry: module base: creating or updating database tables 
2021-06-17 00:39:02,490 19759 INFO teste odoo.models: Computing parent_path for table ir_ui_menu... 
2021-06-17 00:39:43,750 19759 INFO teste odoo.models: Computing parent_path for table res_partner_category... 
2021-06-17 00:40:02,371 19759 INFO teste odoo.models: Storing computed values of ir.model.fields.relation_field_id 
2021-06-17 00:40:02,376 19759 INFO teste odoo.models: Storing computed values of ir.model.fields.related_field_id 
2021-06-17 00:40:02,860 19759 INFO teste odoo.models: Storing computed values of ir.attachment.res_name 
2021-06-17 00:40:02,861 19759 INFO teste odoo.models: Storing computed values of ir.attachment.res_model_name 
2021-06-17 00:40:03,002 19759 INFO teste odoo.models: Storing computed values of ir.rule.global 
2021-06-17 00:40:03,217 19759 INFO teste odoo.models: Storing computed values of ir.module.module.menus_by_module 
2021-06-17 00:40:03,226 19759 INFO teste odoo.models: Storing computed values of ir.module.module.reports_by_module 
2021-06-17 00:40:03,227 19759 INFO teste odoo.models: Storing computed values of ir.module.module.views_by_module 
2021-06-17 00:40:03,474 19759 INFO teste odoo.models: Storing computed values of res.partner.display_name 
2021-06-17 00:40:03,508 19759 INFO teste odoo.models: Storing computed values of res.partner.partner_share 
2021-06-17 00:40:03,510 19759 INFO teste odoo.models: Storing computed values of res.partner.commercial_partner_id 
2021-06-17 00:40:03,512 19759 INFO teste odoo.models: Storing computed values of res.partner.commercial_company_name 
2021-06-17 00:40:03,568 19759 INFO teste odoo.models: Storing computed values of res.partner.bank.sanitized_acc_number 
2021-06-17 00:40:03,650 19759 INFO teste odoo.models: Storing computed values of res.currency.decimal_places 
2021-06-17 00:40:03,695 19759 INFO teste odoo.models: Storing computed values of res.company.logo_web 
2021-06-17 00:40:03,805 19759 INFO teste odoo.models: Storing computed values of res.users.share 
2021-06-17 00:40:04,727 19759 INFO teste odoo.modules.loading: loading base/data/res.lang.csv 
2021-06-17 00:40:04,896 19759 INFO teste odoo.modules.loading: loading base/data/res_lang_data.xml 
2021-06-17 00:40:04,951 19759 INFO teste odoo.modules.loading: loading base/data/res_partner_data.xml 
2021-06-17 00:40:05,336 19759 INFO teste odoo.modules.loading: loading base/data/res_company_data.xml 
2021-06-17 00:40:05,395 19759 INFO teste odoo.modules.loading: loading base/data/res_users_data.xml 
2021-06-17 00:40:05,876 19759 INFO teste odoo.modules.loading: loading base/data/report_paperformat_data.xml 
2021-06-17 00:40:05,910 19759 INFO teste odoo.modules.loading: loading base/data/res_currency_data.xml 
2021-06-17 00:40:06,781 19759 INFO teste odoo.modules.loading: loading base/data/res_country_data.xml 
2021-06-17 00:40:10,399 19759 INFO teste odoo.modules.loading: loading base/data/ir_demo_data.xml 
2021-06-17 00:40:10,473 19759 INFO teste odoo.modules.loading: loading base/security/base_groups.xml 
2021-06-17 00:40:10,868 19759 INFO teste odoo.modules.loading: loading base/security/base_security.xml 
2021-06-17 00:40:11,177 19759 INFO teste odoo.modules.loading: loading base/views/base_menus.xml 
2021-06-17 00:40:11,480 19759 INFO teste odoo.modules.loading: loading base/views/res_config_views.xml 
2021-06-17 00:40:11,551 19759 INFO teste odoo.modules.loading: loading base/data/res.country.state.csv 
2021-06-17 00:40:12,516 19759 INFO teste odoo.modules.loading: loading base/views/ir_actions_views.xml 
2021-06-17 00:40:13,051 19759 INFO teste odoo.modules.loading: loading base/views/ir_config_parameter_views.xml 
2021-06-17 00:40:13,162 19759 INFO teste odoo.modules.loading: loading base/views/ir_cron_views.xml 
2021-06-17 00:40:13,361 19759 INFO teste odoo.modules.loading: loading base/views/ir_filters_views.xml 
2021-06-17 00:40:13,472 19759 INFO teste odoo.modules.loading: loading base/views/ir_mail_server_views.xml 
2021-06-17 00:40:13,592 19759 INFO teste odoo.modules.loading: loading base/views/ir_model_views.xml 
2021-06-17 00:40:14,163 19759 INFO teste odoo.modules.loading: loading base/views/ir_attachment_views.xml 
2021-06-17 00:40:14,308 19759 INFO teste odoo.modules.loading: loading base/views/ir_rule_views.xml 
2021-06-17 00:40:14,444 19759 INFO teste odoo.modules.loading: loading base/views/ir_sequence_views.xml 
2021-06-17 00:40:14,611 19759 INFO teste odoo.modules.loading: loading base/views/ir_translation_views.xml 
2021-06-17 00:40:14,756 19759 INFO teste odoo.modules.loading: loading base/views/ir_ui_menu_views.xml 
2021-06-17 00:40:14,896 19759 INFO teste odoo.modules.loading: loading base/views/ir_ui_view_views.xml 
2021-06-17 00:40:15,136 19759 INFO teste odoo.modules.loading: loading base/views/ir_default_views.xml 
2021-06-17 00:40:15,254 19759 INFO teste odoo.modules.loading: loading base/data/ir_cron_data.xml 
2021-06-17 00:40:15,297 19759 INFO teste odoo.modules.loading: loading base/report/ir_model_report.xml 
2021-06-17 00:40:15,340 19759 INFO teste odoo.modules.loading: loading base/report/ir_model_templates.xml 
2021-06-17 00:40:15,381 19759 INFO teste odoo.modules.loading: loading base/views/ir_logging_views.xml 
2021-06-17 00:40:15,493 19759 INFO teste odoo.modules.loading: loading base/views/ir_qweb_widget_templates.xml 
2021-06-17 00:40:15,546 19759 INFO teste odoo.modules.loading: loading base/views/ir_module_views.xml 
2021-06-17 00:40:15,839 19759 INFO teste odoo.modules.loading: loading base/data/ir_module_category_data.xml 
2021-06-17 00:40:16,047 19759 INFO teste odoo.modules.loading: loading base/data/ir_module_module.xml 
2021-06-17 00:40:16,258 19759 INFO teste odoo.modules.loading: loading base/report/ir_module_reports.xml 
2021-06-17 00:40:16,287 19759 INFO teste odoo.modules.loading: loading base/report/ir_module_report_templates.xml 
2021-06-17 00:40:16,323 19759 INFO teste odoo.modules.loading: loading base/wizard/base_module_update_views.xml 
2021-06-17 00:40:16,395 19759 INFO teste odoo.modules.loading: loading base/wizard/base_language_install_views.xml 
2021-06-17 00:40:16,512 19759 INFO teste odoo.modules.loading: loading base/wizard/base_import_language_views.xml 
2021-06-17 00:40:16,600 19759 INFO teste odoo.modules.loading: loading base/wizard/base_module_upgrade_views.xml 
2021-06-17 00:40:16,730 19759 INFO teste odoo.modules.loading: loading base/wizard/base_module_uninstall_views.xml 
2021-06-17 00:40:16,785 19759 INFO teste odoo.modules.loading: loading base/wizard/base_export_language_views.xml 
2021-06-17 00:40:16,859 19759 INFO teste odoo.modules.loading: loading base/wizard/base_update_translations_views.xml 
2021-06-17 00:40:16,917 19759 INFO teste odoo.modules.loading: loading base/wizard/base_partner_merge_views.xml 
2021-06-17 00:40:16,981 19759 INFO teste odoo.modules.loading: loading base/data/ir_actions_data.xml 
2021-06-17 00:40:17,027 19759 INFO teste odoo.modules.loading: loading base/data/ir_demo_failure_data.xml 
2021-06-17 00:40:17,092 19759 INFO teste odoo.modules.loading: loading base/views/res_company_views.xml 
2021-06-17 00:40:17,376 19759 INFO teste odoo.modules.loading: loading base/views/res_lang_views.xml 
2021-06-17 00:40:17,518 19759 INFO teste odoo.modules.loading: loading base/views/res_partner_views.xml 
2021-06-17 00:40:18,074 19759 INFO teste odoo.modules.loading: loading base/views/res_bank_views.xml 
2021-06-17 00:40:18,237 19759 INFO teste odoo.modules.loading: loading base/views/res_country_views.xml 
2021-06-17 00:40:18,452 19759 INFO teste odoo.modules.loading: loading base/views/res_currency_views.xml 
2021-06-17 00:40:18,692 19759 INFO teste odoo.modules.loading: loading base/views/res_users_views.xml 
2021-06-17 00:40:19,270 19759 INFO teste odoo.modules.loading: loading base/views/ir_property_views.xml 
2021-06-17 00:40:19,413 19759 INFO teste odoo.modules.loading: loading base/views/res_config_settings_views.xml 
2021-06-17 00:40:19,447 19759 INFO teste odoo.modules.loading: loading base/views/report_paperformat_views.xml 
2021-06-17 00:40:19,570 19759 INFO teste odoo.modules.loading: loading base/views/onboarding_views.xml 
2021-06-17 00:40:19,752 19759 INFO teste odoo.modules.loading: loading base/security/ir.model.access.csv 
2021-06-17 00:40:20,322 19759 INFO teste odoo.addons.base.models.ir_translation: module base: loading base translation file pt for language pt_BR 
2021-06-17 00:40:20,323 19759 INFO teste odoo.tools.translate: loading /opt/odoo/odoo/odoo/addons/base/i18n/pt.po 
2021-06-17 00:40:21,143 19759 INFO teste odoo.addons.base.models.ir_translation: module base: loading translation file (pt_BR) for language pt_BR 
2021-06-17 00:40:21,143 19759 INFO teste odoo.tools.translate: loading /opt/odoo/odoo/odoo/addons/base/i18n/pt_BR.po 
2021-06-17 00:40:22,181 19759 INFO teste odoo.modules.loading: 1 modules loaded in 91.46s, 0 queries 
2021-06-17 00:40:22,252 19759 INFO teste odoo.addons.base.models.ir_translation: module base: loading base translation file pt for language pt_BR 
2021-06-17 00:40:22,252 19759 INFO teste odoo.tools.translate: loading /opt/odoo/odoo/odoo/addons/base/i18n/pt.po 
2021-06-17 00:40:22,879 19759 INFO teste odoo.addons.base.models.ir_translation: module base: loading translation file (pt_BR) for language pt_BR 
2021-06-17 00:40:22,879 19759 INFO teste odoo.tools.translate: loading /opt/odoo/odoo/odoo/addons/base/i18n/pt_BR.po 
2021-06-17 00:40:23,656 19759 INFO teste odoo.modules.loading: updating modules list 
2021-06-17 00:40:23,657 19759 INFO teste odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via 127.0.0.1 
2021-06-17 00:40:26,298 19759 INFO teste odoo.modules.loading: loading 11 modules... 
2021-06-17 00:40:26,497 19759 INFO teste odoo.modules.registry: module web: creating or updating database tables 
2021-06-17 00:40:27,993 19759 INFO teste odoo.modules.loading: loading web/security/ir.model.access.csv 
2021-06-17 00:40:28,048 19759 INFO teste odoo.modules.loading: loading web/views/webclient_templates.xml 
2021-06-17 00:40:28,564 19759 INFO teste odoo.modules.loading: loading web/views/report_templates.xml 
2021-06-17 00:40:29,017 19759 INFO teste odoo.modules.loading: loading web/data/res_company.xml 
2021-06-17 00:40:29,074 19759 INFO teste odoo.modules.loading: loading web/data/report_layout.xml 
2021-06-17 00:40:29,218 19759 INFO teste odoo.addons.base.models.ir_translation: module web: loading base translation file pt for language pt_BR 
2021-06-17 00:40:29,236 19759 INFO teste odoo.tools.translate: loading /opt/odoo/odoo/addons/web/i18n/pt.po 
2021-06-17 00:40:29,430 19759 INFO teste odoo.addons.base.models.ir_translation: module web: loading translation file (pt_BR) for language pt_BR 
2021-06-17 00:40:29,430 19759 INFO teste odoo.tools.translate: loading /opt/odoo/odoo/addons/web/i18n/pt_BR.po 
2021-06-17 00:40:31,095 19759 INFO teste odoo.modules.registry: module base_import: creating or updating database tables 
2021-06-17 00:40:38,195 19759 INFO teste odoo.modules.loading: loading base_import/security/ir.model.access.csv 
2021-06-17 00:40:38,341 19759 INFO teste odoo.modules.loading: loading base_import/views/base_import_templates.xml 
2021-06-17 00:40:38,538 19759 INFO teste odoo.addons.base.models.ir_translation: module base_import: loading base translation file pt for language pt_BR 
2021-06-17 00:40:38,538 19759 INFO teste odoo.tools.translate: loading /opt/odoo/odoo/addons/base_import/i18n/pt.po 
2021-06-17 00:40:38,590 19759 INFO teste odoo.addons.base.models.ir_translation: module base_import: loading translation file (pt_BR) for language pt_BR 
2021-06-17 00:40:38,590 19759 INFO teste odoo.tools.translate: loading /opt/odoo/odoo/addons/base_import/i18n/pt_BR.po 
2021-06-17 00:40:41,569 19759 INFO teste odoo.modules.registry: module br_base: creating or updating database tables 
2021-06-17 00:40:44,080 19759 WARNING teste odoo.addons.base.models.ir_model: Two fields (city_id, city) of res.company() have the same label: City. 
2021-06-17 00:40:44,142 19759 WARNING teste odoo.addons.base.models.ir_model: Two fields (city_id, city) of res.partner() have the same label: City. 
2021-06-17 00:40:44,185 19759 WARNING teste odoo.addons.base.models.ir_model: Two fields (city_id, city) of res.bank() have the same label: City. 
2021-06-17 00:40:44,185 19759 WARNING teste odoo.addons.base.models.ir_model: Two fields (country_id, country) of res.bank() have the same label: Country. 
2021-06-17 00:40:44,231 19759 WARNING teste odoo.addons.base.models.ir_model: Two fields (city_id, city) of res.users() have the same label: City. 
2021-06-17 00:40:44,328 19759 INFO teste odoo.modules.loading: loading br_base/views/br_base.xml 
2021-06-17 00:40:44,431 19759 INFO teste odoo.modules.loading: loading br_base/views/ir_module.xml 
2021-06-17 00:40:44,499 19759 INFO teste odoo.modules.loading: loading br_base/views/br_base_view.xml 
2021-06-17 00:40:44,531 19759 WARNING teste odoo.modules.loading: Transient module states were reset 
2021-06-17 00:40:44,568 19759 ERROR teste odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/res_country.py", line 104, in _check_address_format
    record.address_format % {i: 1 for i in address_fields}
KeyError: 'city_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/models.py", line 1128, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_country.py", line 106, in _check_address_format
    raise UserError(_('The layout contains an invalid format key'))
odoo.exceptions.UserError: ('O layout contém um formato de chave inválida', '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo/odoo/odoo/models.py", line 3881, in _load_records
    data['record']._load_records_write(data['values'])
  File "/opt/odoo/odoo/odoo/models.py", line 3819, in _load_records_write
    self.write(values)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_country.py", line 91, in write
    return super(Country, self).write(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3364, in write
    self._write(store_vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3500, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 1132, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nO layout contém um formato de chave inválida\n', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo/odoo/odoo/models.py", line 3881, in _load_records
    data['record']._load_records_write(data['values'])
  File "/opt/odoo/odoo/odoo/models.py", line 3819, in _load_records_write
    self.write(values)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_country.py", line 91, in write
    return super(Country, self).write(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3364, in write
    self._write(store_vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3500, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 1132, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

O layout contém um formato de chave inválida

None" while parsing /opt/odoo/odoo/addons-custom/odoo-brasil/br_base/views/br_base_view.xml:4, near
<record id="base.br" model="res.country">
        <field name="address_format" eval="'%(street)s, %(number)s - %(street2)s\n%(district)s\n%(zip)s - %(city_name)s - %(state_code)s\n%(country_name)s'"/>
    </record>
2021-06-17 00:40:44,660 19759 ERROR teste odoo.service.db: CREATE DATABASE failed: 
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/res_country.py", line 104, in _check_address_format
    record.address_format % {i: 1 for i in address_fields}
KeyError: 'city_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/models.py", line 1128, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_country.py", line 106, in _check_address_format
    raise UserError(_('The layout contains an invalid format key'))
odoo.exceptions.UserError: ('O layout contém um formato de chave inválida', '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo/odoo/odoo/models.py", line 3881, in _load_records
    data['record']._load_records_write(data['values'])
  File "/opt/odoo/odoo/odoo/models.py", line 3819, in _load_records_write
    self.write(values)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_country.py", line 91, in write
    return super(Country, self).write(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3364, in write
    self._write(store_vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3500, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 1132, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nO layout contém um formato de chave inválida\n', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/service/db.py", line 62, in _initialize_db
    registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo/odoo/odoo/models.py", line 3881, in _load_records
    data['record']._load_records_write(data['values'])
  File "/opt/odoo/odoo/odoo/models.py", line 3819, in _load_records_write
    self.write(values)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_country.py", line 91, in write
    return super(Country, self).write(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3364, in write
    self._write(store_vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3500, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 1132, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

O layout contém um formato de chave inválida

None" while parsing /opt/odoo/odoo/addons-custom/odoo-brasil/br_base/views/br_base_view.xml:4, near
<record id="base.br" model="res.country">
        <field name="address_format" eval="'%(street)s, %(number)s - %(street2)s\n%(district)s\n%(zip)s - %(city_name)s - %(state_code)s\n%(country_name)s'"/>
    </record>
2021-06-17 00:40:44,671 19759 INFO teste odoo.modules.loading: loading 1 modules... 
2021-06-17 00:40:44,703 19759 INFO teste odoo.modules.loading: 1 modules loaded in 0.03s, 0 queries 
2021-06-17 00:40:44,706 19759 INFO teste odoo.modules.loading: loading 2 modules... 
2021-06-17 00:40:44,711 19759 INFO teste odoo.modules.loading: 2 modules loaded in 0.01s, 0 queries 
2021-06-17 00:40:44,927 19759 INFO teste odoo.modules.loading: Modules loaded. 
2021-06-17 00:40:44,932 19759 INFO teste odoo.addons.base.models.res_users: Login failed for db:teste login:gglimass@hotmail.com from 127.0.0.1 
2021-06-17 00:40:45,163 19759 INFO teste werkzeug: 127.0.0.1 - - [17/Jun/2021 00:40:45] "POST /web/database/create HTTP/1.1" 200 - 25276 103.255 25.441
2021-06-17 00:40:51,595 19759 INFO teste odoo.addons.base.models.ir_cron: Starting job `Base: Auto-vacuum internal data`. 
2021-06-17 00:40:51,685 19759 INFO teste odoo.addons.base.models.ir_attachment: filestore gc 244 checked, 0 removed 
2021-06-17 00:40:51,710 19759 INFO teste odoo.addons.base.models.ir_autovacuum: GC'd 0 user log entries 
2021-06-17 00:40:51,742 19759 INFO teste odoo.addons.base.models.ir_cron: Job `Base: Auto-vacuum internal data` done.

**Comment by gilsonlima10** [comment]
existe previsão para correção deste BUG?

**Comment by danimaribeiro** [comment]
versão 12 não vai ser corrigida.
