### ISSUE TITLE
Erro ao Terminar Processo de Importação com IPI na NF e sugestão de melhoria.

### ISSUE THREAD

**Issue by rodmad85** [Trust-Code/odoo-brasil#1141]
Boa tarde Srs.
Está ocorrendo este erro em NF's que possuem cobrança com IPI.
Fiz uma alteração manualmente na listagem de NF's incluindo o número de NF do fornecedor e na pesquisa também para facilitar a localização das notas.
Sugestão: no botão ação ao selecionar diversas NF's, a opção de "Terminar processo de importação" para agilizar o processo de lançamento das NF's no financeiro, para isso incluir um filtro em todas as NF's que contenham cobrança.
Estou me aperfeiçoando no Odoo, e assim que puder gostaria de contribuir com os módulos da Trust-Code e futuramente fazermos uma parceria.
Abraço!

Traceback (most recent call last):
  File "/home/odoo/odoo14/core/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo14/core/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: External ID not found in the system: l10n_br_nfe_import.product_product_tax_ipi

**Comment by rodmad85** [comment]
Poderia também incluir o campo de NF em pedido de compra e no recebimento para acompanhamento.

**Comment by rodmad85** [comment]
A Natureza da Operação também não esta sendo preenchida, fiz uma alteração manualmente aqui e estou testando.

**Comment by rodmad85** [comment]
Consegui corrigir atualizando o modulo de eletronic documents.
