### ISSUE TITLE
Erro no parte de contas a receber/pagar. 

### ISSUE THREAD

**Issue by thiagoblisboa** [Trust-Code/odoo-brasil#1153]
Olá, tudo bem? 
Estou tendo o seguinte erro no módulo de contas a pagar e receber…  Alguém poderia me ajudar, por favor?

RPC_ERROR
Odoo Server Error

Traceback (most recent call last):
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/cloudclusters/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/cloudclusters/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/cloudclusters/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/cloudclusters/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/cloudclusters/odoo/odoo/addons/web/controllers/main.py", line 1339, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/cloudclusters/odoo/odoo/addons/web/controllers/main.py", line 1327, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/cloudclusters/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/cloudclusters/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/addons/l10n_br_account/models/account_move.py", line 254, in action_register_payment_move_line
    dummy, act_id = self.env["ir.model.data"].get_object_reference(
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cloudclusters/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/cloudclusters/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'ir.model.data' object has no attribute 'get_object_reference'

**Comment by fabioluna** [comment]
> Olá, tudo bem? Estou tendo o seguinte erro no módulo de contas a pagar e receber… Alguém poderia me ajudar, por favor?
> 
> RPC_ERROR Odoo Server Error
> 
> Traceback (most recent call last): File "/cloudclusters/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch result = request.dispatch() File "/cloudclusters/odoo/odoo/http.py", line 687, in dispatch result = self._call_function(**self.params) File "/cloudclusters/odoo/odoo/http.py", line 359, in _call_function return checked_call(self.db, *args, **kwargs) File "/cloudclusters/odoo/odoo/service/model.py", line 94, in wrapper return f(dbname, *args, **kwargs) File "/cloudclusters/odoo/odoo/http.py", line 348, in checked_call result = self.endpoint(*a, **kw) File "/cloudclusters/odoo/odoo/http.py", line 916, in **call** return self.method(*args, **kw) File "/cloudclusters/odoo/odoo/http.py", line 535, in response_wrap response = f(*args, **kw) File "/cloudclusters/odoo/odoo/addons/web/controllers/main.py", line 1339, in call_button action = self._call_kw(model, method, args, kwargs) File "/cloudclusters/odoo/odoo/addons/web/controllers/main.py", line 1327, in _call_kw return call_kw(request.env[model], method, args, kwargs) File "/cloudclusters/odoo/odoo/api.py", line 464, in call_kw result = _call_kw_multi(method, model, args, kwargs) File "/cloudclusters/odoo/odoo/api.py", line 451, in _call_kw_multi result = method(recs, *args, **kwargs) File "/cloudclusters/odoo/odoo/addons/l10n_br_account/models/account_move.py", line 254, in action_register_payment_move_line dummy, act_id = self.env["ir.model.data"].get_object_reference( Exception
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/cloudclusters/odoo/odoo/http.py", line 643, in _handle_exception return super(JsonRequest, self)._handle_exception(exception) File "/cloudclusters/odoo/odoo/http.py", line 301, in _handle_exception raise exception.with_traceback(None) from new_cause AttributeError: 'ir.model.data' object has no attribute 'get_object_reference'

Qual versão do Odoo você está utilizando? Consegue descrever o passo a passo do que você está tentando executar para podermos reproduzir?

**Comment by thiagoblisboa** [comment]
Olá @fabioluna muito obrigado… 

Utilizo a versão 15. 

Quando vou clicar no link de contas a pagar/receber e vou efetuar o pagamento por lá, o erro aparece. 
Imagem anexa..
![pagar receber](https://user-images.githubusercontent.com/38355984/151903741-a2d325e1-60e7-448a-ac4f-f98c08b52a5d.png)
![pagar receber](https://user-images.githubusercontent.com/38355984/151903754-2fba7241-2ed6-4d3a-8c5e-47af9d4d9e13.png)
.

**Comment by thiagoblisboa** [comment]
Pessoal, alguém consegue ajudar?

**Comment by LorranLyM** [comment]
Eu resolvi este problema utilizando a seguinte função: check_object_reference(). A get_object_reference() já não está presente em odoo 15. Link referencia: https://www.odoo.com/pt_BR/forum/ajuda-1/odoo-v15-xmlrpc-changed-get-object-reference-shortcut-to-xmlid-lookup-199052
