### ISSUE TITLE
Erro geração de NF - Pedido de Compra

### ISSUE THREAD

**Issue by GuilhermeKimoto** [Trust-Code/odoo-brasil#1198]
![image](https://user-images.githubusercontent.com/70413601/169393004-3d27004b-081f-4b98-a3d6-4927257e0bcd.png)
Olá, estou enfrentando este erro ao tentar gerar uma NF.
Isso já foi solucionado?
O que poderia gerar este erro?

Odoo 14 Community

Desde já agradeço.

Erro:
Odoo Server Error

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
result = request.dispatch()
File "/usr/lib/python3/dist-packages/odoo/http.py", line 685, in dispatch
result = self._call_function(**self.params)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 361, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
return f(dbname, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 349, in checked_call
result = self.endpoint(*a, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 914, in __call__
return self.method(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 533, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1398, in call_button
action = self._call_kw(model, method, args, kwargs)
File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1386, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
result = _call_kw_multi(method, model, args, kwargs)
File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
result = method(recs, *args, **kwargs)
File "/mnt/extras_addons/odoo-brasil/l10n_br_eletronic_document/models/account_move.py", line 412, in action_create_eletronic_document
self._create_product_eletronic_document(move, products)
File "/mnt/extras_addons/odoo-brasil/l10n_br_eletronic_document/models/account_move.py", line 424, in _create_product_eletronic_document
numero_nfe = self.company_id.l10n_br_nfe_sequence.next_by_id()
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_sequence.py", line 271, in next_by_id
return self._next(sequence_date=sequence_date)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_sequence.py", line 260, in _next
return self._next_do()
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_sequence.py", line 201, in _next_do
number_next = _update_nogap(self, self.number_increment)
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_sequence.py", line 56, in _update_nogap
self._cr.execute("SELECT number_next FROM %s WHERE id=%%s FOR UPDATE NOWAIT" % self._table, [self.id])
File "<decorator-gen-3>", line 2, in execute
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 101, in check
return f(self, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 298, in execute
res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/http.py", line 641, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 317, in _handle_exception
raise exception.with_traceback(None) from new_cause
psycopg2.errors.UndefinedFunction: operator does not exist: integer = boolean
LINE 1: SELECT number_next FROM ir_sequence WHERE id=false FOR UPDAT...
^
HINT: No operator matches the given name and argument types. You might need to add explicit type casts.

**Comment by fabioluna** [comment]
Está faltando configurar a sequência da NF-e lá nas configurações da contabilidade.

**Comment by GuilhermeKimoto** [comment]
@fabioluna muito obrigado! evoluímos no erro.

E gerou essas outras dúvidas, espero que possa contribuir.

Ao tentar  visualizar a Danfe.
![image](https://user-images.githubusercontent.com/70413601/169402088-b4c8088f-381a-44b9-85c3-03c14c476b6c.png)

Enviar para o cliente.
![image](https://user-images.githubusercontent.com/70413601/169402145-f71ce8ed-43c7-4f56-959a-da2e47360783.png)
