### ISSUE TITLE
Emissão NFSe GINFES

### ISSUE THREAD

**Issue by rodrigoatdata** [Trust-Code/odoo-brasil#1215]
Boa tarde !

Por gentileza gostaria de ajuda para configurar a emissão de NFSe - da prefeitura de  Guarulhos -SP.
Instalei o modulo com sucesso na versão 14 do Odoo.
Ao tentar emitir gerou um RPS em PDF com layout muito bonito. Porem ao clicar em enviar nada acontece e ao clicar em validar XML exibe o seguinte erro:

Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo14/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo14/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14/addons/web/controllers/main.py", line 1398, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo14/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo14/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo14/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo14/odoo-custom-addons/l10n_br_fiscal/models/document_eletronic.py", line 209, in view_xml
    self._document_export()
  File "/opt/odoo14/odoo-custom-addons/l10n_br_nfse/models/document.py", line 128, in _document_export
    edoc = record.serialize()[0]
  File "/opt/odoo14/odoo-custom-addons/l10n_br_fiscal/models/document_eletronic.py", line 189, in serialize
    self._serialize(edocs)
  File "/opt/odoo14/odoo-custom-addons/l10n_br_nfse_ginfes/models/document.py", line 60, in _serialize
    edocs.append(record.serialize_nfse_ginfes())
  File "/opt/odoo14/odoo-custom-addons/l10n_br_nfse_ginfes/models/document.py", line 206, in serialize_nfse_ginfes
    LoteRps=self._serialize_ginfes_lote_rps()
  File "/opt/odoo14/odoo-custom-addons/l10n_br_nfse_ginfes/models/document.py", line 200, in _serialize_ginfes_lote_rps
    Rps=[self._serialize_ginfes_rps(dados)]
  File "/opt/odoo14/odoo-custom-addons/l10n_br_nfse_ginfes/models/document.py", line 174, in _serialize_ginfes_rps
    Servico=self._serialize_ginfes_dados_servico(),
  File "/opt/odoo14/odoo-custom-addons/l10n_br_nfse_ginfes/models/document.py", line 64, in _serialize_ginfes_dados_servico
    self.line_ids.ensure_one()
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'l10n_br_fiscal.document' object has no attribute 'line_ids'

**Comment by danimaribeiro** [comment]
Esses módulos não são desse repositório.
