### ISSUE TITLE
Função de validação de CNAB inexistente no código

### ISSUE THREAD

**Issue by Rynaro** [Trust-Code/odoo-brasil#143]
Na tela de Ordens de Cobrança, temos dois botões **Gerar CNAB** e **Validar CNAB**. As funcionalidades do **Gerar CNAB** estão corretas, porém, ao tentar acionar o **Validar CNAB**, um erro ocorre e dispara o seguinte trace:

````
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/ubuntu/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/ubuntu/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/ubuntu/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/ubuntu/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/ubuntu/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/ubuntu/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/ubuntu/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/ubuntu/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/ubuntu/odoo/odoo/api.py", line 677, in call_kw
    method = getattr(type(model), name)
AttributeError: type object 'payment.order' has no attribute 'validar_cnab'
````

Fazendo um busca no repositório clonado, não localizei a função  `validar_cnab` no módulo **br_cnab**.  E olhando o código de front-end, é possível notar que esta função está sendo procurada neste módulo, assim como o botão que gera.

**Comment by danimaribeiro** [comment]
Fixed
