### ISSUE TITLE
erro no cancelamento de nfe

### ISSUE THREAD

**Issue by ewertonmagalhaes** [Trust-Code/odoo-brasil#146]
ao clicar em cancelar documento nfe

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/var/lib/odoo/addons/odoo-brasil/br_nfe/wizard/cancel_nfe.py", line 19, in action_cancel_nfe
    justificativa=self.justificativa)
  File "/var/lib/odoo/addons/odoo-brasil/br_nfe/models/invoice_eletronic.py", line 835, in action_cancel_document
    resp = recepcao_evento_cancelamento(certificado, **cancelamento)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/__init__.py", line 196, in recepcao_evento_cancelamento
    return _send(certificado, 'RecepcaoEventoCancelamento', True, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/__init__.py", line 175, in _send
    kwargs['ambiente'])
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/Servidores.py", line 83, in localizar_url
    complemento = ws[ambiente][servico]
KeyError: 'RecepcaoEventoCancelamento'

**Comment by danimaribeiro** [comment]
Qual o estado?

**Comment by ewertonmagalhaes** [comment]
minas gerais

**Comment by danimaribeiro** [comment]
Acho que foi corrigido neste commit.
Porém não tenho como testar.

**Comment by danimaribeiro** [comment]
Caso o erro persista você pode reabrir o Issue.
