### ISSUE TITLE
Erro ao abrir Odoo

### ISSUE THREAD

**Issue by rodriguesraphael** [Trust-Code/odoo-brasil#18]
Pessoal, eu estava criando uma base para testes, instalei os módulos da TrustCode para Vendas e depois de sair do sistema, ao logar novamente a tela mostra o logo apenas, segue o log abaixo, nele mostra um erro.

2016-12-15 00:30:33,205 2437 INFO demo1-dist odoo.addons.base.ir.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/demo1-dist/63/636cbb02acab8c81faf536229fa201ecd7813e8c
Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] Ficheiro ou directoria inexistente: u'/home/odoo/.local/share/Odoo/filestore/demo1-dist/63/636cbb02acab8c81faf536229fa201ecd7813e8c'
2016-12-15 00:30:33,227 2437 INFO demo1-dist werkzeug: 192.168.1.103 - - [15/Dec/2016 00:30:33] "GET /web/content/250-596c9b0/web_editor.assets_editor.0.css HTTP/1.1" 200 -
2016-12-15 00:30:33,253 2437 INFO demo1-dist odoo.addons.base.ir.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/demo1-dist/6d/6d16b67e0ef2f9351cbc64d436368b4ed76e8d73
Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] Ficheiro ou directoria inexistente: u'/home/odoo/.local/share/Odoo/filestore/demo1-dist/6d/6d16b67e0ef2f9351cbc64d436368b4ed76e8d73'
2016-12-15 00:30:33,276 2437 INFO demo1-dist odoo.addons.base.ir.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/demo1-dist/47/47125285257df977cd72ced724933149bed51158
Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] Ficheiro ou directoria inexistente: u'/home/odoo/.local/share/Odoo/filestore/demo1-dist/47/47125285257df977cd72ced724933149bed51158'
2016-12-15 00:30:33,277 2437 INFO demo1-dist werkzeug: 192.168.1.103 - - [15/Dec/2016 00:30:33] "GET /web/content/253-e9f9dbe/web_editor.summernote.js HTTP/1.1" 200 -
2016-12-15 00:30:33,282 2437 INFO demo1-dist werkzeug: 192.168.1.103 - - [15/Dec/2016 00:30:33] "GET /web/content/254-596c9b0/web_editor.assets_editor.js HTTP/1.1" 200 -
2016-12-15 00:30:33,339 2437 INFO demo1-dist werkzeug: 192.168.1.103 - - [15/Dec/2016 00:30:33] "GET /web/binary/company_logo HTTP/1.1" 200 -
2016-12-15 00:30:33,405 2437 INFO demo1-dist werkzeug: 192.168.1.103 - - [15/Dec/2016 00:30:33] "GET /web/content/303-7e5bbd3/web.assets_backend.js HTTP/1.1" 200 -
2016-12-15 00:30:33,614 2437 INFO ? werkzeug: 192.168.1.103 - - [15/Dec/2016 00:30:33] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 -
2016-12-15 00:30:50,712 2437 INFO demo1-dist werkzeug: 192.168.1.103 - - [15/Dec/2016 00:30:50] "GET /web HTTP/1.1" 200 -
2016-12-15 00:31:19,120 2437 INFO demo1-dist werkzeug: 192.168.1.103 - - [15/Dec/2016 00:31:19] "POST /longpolling/poll HTTP/1.1" 200 -
^C2016-12-15 00:35:43,596 2437 INFO ? odoo.service.server: Initiating shutdown
2016-12-15 00:35:43,597 2437 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

**Comment by danimaribeiro** [comment]
Geralmente ocorre um erro logo na inicialização do Odoo.
Tem que investigar o stack trace completo e procurar por outro tipo de erro.

**Comment by rodriguesraphael** [comment]
Com qual comando eu verifico o Stack inteiro?

**Comment by danimaribeiro** [comment]
Você deve olhar o arquivo inteiro de log.

**Comment by crsilveira** [comment]
consegui sair disso deletando estes itens da tabela :  delete FROM "public"."ir_attachment"
WHERE
"public"."ir_attachment"."store_fname" LIKE '%9739bf1f391e10051ed840fef5b341f9351d0536%'

acho q acontece devido ao usuário q vc executa o odoo, meu caso executei com o usuário odoo , depois chamei pelo supervisor usando o odoo tbém, mas dai deu este problema.

Fonte:
https://www.odoo.com/forum/help-1/question/ir-attachment-ioerror-errno-2-no-such-file-or-directory-94675

**Comment by danimaribeiro** [comment]
Resolveu seu problema?

**Comment by rodriguesraphael** [comment]
Sim até foi, mas como faz alguns dias eu não sei reportar o procedimento com certeza, mas acredito que criei outro banco de dados, e para tentar reproduzir o mesmo erro instalei os mesmos modulos e cadastrando os mesmos produtos utilizando as mesmas imagens, porém o erro não foi retornado.
Minha VM estava com pouco espaço, cerca de 170MB, eu estava com problemas tbm para realizar backups do banco, talvez o erro também tivesse algo em relação a este problema de espaço em disco.

---
Danimar aonde podemos postar dúvidas referente a localização?
Estou testando e verificando e notei que na entrada(Compras) os impostos não são carregados automaticamente como ocorre nas vendas, não sei se tem algum motivo especifico, se não tiver eu iria tentar escrever alguma forma dos impostos serem carregados automaticamente da mesma forma do vendas.

**Comment by danimaribeiro** [comment]
Ainda não foi implementado em compras.
Mas geralmente os impostos são cadastrados apenas na fatura, pois dependem da nota que o fornecedor emitiu.

**Comment by rodriguesraphael** [comment]
Exato, isso é a prática correta, mas empresas pequenas e até médias usam um
fluxo menor, eles não usam pedidos de compras no sistema, apenas compram e
lançam a entrada pela nota fiscal.

Em ter, 20 de dez de 2016 13:23, Danimar Ribeiro <notifications@github.com>
escreveu:
