### ISSUE TITLE
Erro ao gerar remessa boleto Itaú

### ISSUE THREAD

**Issue by gvicentes** [Trust-Code/odoo-brasil#190]
Olá,
Os Boletos são gerados com sucesso após validação da fatura e lançados automaticamente em Ordens de Cobrança. 
Quando mando gerar CNAB ocorre o seguinte erro:
`Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/trust/odoo-brasil/br_cnab/models/payment_order.py", line 32, in gerar_cnab
    remessa = cnab.remessa(order)
  File "/opt/odoo/trust/odoo-brasil/br_cnab/febraban/cnab_240/cnab_240.py", line 234, in remessa
    self.arquivo = Arquivo(self.bank, **header)
  File "/usr/local/lib/python2.7/dist-packages/cnab240/tipos.py", line 136, in __init__
    self.header = self.banco.registros.HeaderArquivo(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cnab240/registro.py", line 138, in __init__
    self.fromdict(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cnab240/registro.py", line 164, in fromdict
    setattr(self, key, value)
  File "/usr/local/lib/python2.7/dist-packages/cnab240/registro.py", line 98, in __set__
    self.valor = value
  File "/usr/local/lib/python2.7/dist-packages/cnab240/registro.py", line 31, in valor
    raise errors.TipoError(self, valor)
TipoError: campo:cedente_convenio formato:alfa decimais:0 digitos:20 - valor:False`

Parece ser alguma situação referente ao Código Convênio na configuração do boleto. Verificando com o Banco, me foi informado que a cobrança deles não usa esse código e portando poderia deixar em branco ou usar o número da conta para validar. Em nenhuma das duas situações obtive sucesso.

**Comment by danimaribeiro** [comment]
Oficialmente o boleto do Itaú não está implementado.
Você pode patrocinar o desenvolvimento do mesmo se tiver interesse.

**Comment by danimaribeiro** [comment]
O Itaú ainda não foi implementado. Fechando o issue.
