### ISSUE TITLE
Erro ao Gerar a DANFE

### ISSUE THREAD

**Issue by eduardotd** [Trust-Code/odoo-brasil#22]
Continuo testando o ODOO 10 com o pacote odoo-brasil

Estou testando a configuração para um MEI.

Consegui ir até o status enviado com a NFE.

Na hora de gerar a DANFE deu o seguinte erro:

Traceback (most recent call last):
  File "/home/odoo/odoo/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/home/odoo/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/home/odoo/odoo/addons/report/models/report.py", line 178, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/home/odoo/odoo/addons/report/models/report.py", line 144, in get_html
    return self.render(report.report_name, docargs)
  File "/home/odoo/odoo/addons/report/models/report.py", line 120, in render
    return view_obj.render_template(template, values)
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1029, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/odoo/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: expected string or buffer
Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_br_nfe_template_br_nfe_danfe_332
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 269, in _get_field
    content = converter.record_to_html(record, field_name, field_options)
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_qweb/fields.py", line 102, in record_to_html
    value = record[field_name]
  File "/home/odoo/odoo/odoo/models.py", line 5180, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/odoo/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "/home/odoo/odoo/odoo/fields.py", line 980, in determine_value
    self.compute_value(recs)
  File "/home/odoo/odoo/odoo/fields.py", line 935, in compute_value
    self._compute_value(records)
  File "/home/odoo/odoo/odoo/fields.py", line 926, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/odoo/addons/br_nfe/models/invoice_eletronic.py", line 32, in _format_danfe_key
    item.chave_nfe, 10, re.DOTALL)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

Error to render compiling AST
TypeError: expected string or buffer
Template: br_nfe.template_br_nfe_danfe
Path: /templates/t/div[1]/div/div[2]/div[3]/div[2]/div/span[2]
Node: <span t-field="o.chave_nfe_danfe" style="font-size:12px;"/>

**Comment by eduardotd** [comment]
Seguem XMLs da NFE
E Screen Shots
![captura de tela de 2016-12-18 09 17 00](https://cloud.githubusercontent.com/assets/9867613/21293173/b4df4066-c503-11e6-9e62-b23e3ee143e9.png)
![captura de tela de 2016-12-18 09 16 43](https://cloud.githubusercontent.com/assets/9867613/21293174/b4e40ad8-c503-11e6-8d39-83d3395c020d.png)






[envio.zip](https://github.com/Trust-Code/odoo-brasil/files/659382/envio.zip)

**Comment by danimaribeiro** [comment]
Se você editar o documento eletrônico e atualizar o campo Chave NFe com o valor retornado.
"35161217312306000186550010000000011000000013" vai conseguir emitir o Danfe.

Sabe me dizer se isto está acontecendo em todas as notas ou foi apenas esta?

**Comment by eduardotd** [comment]
Opa!

Não achei onde atualizar a chave na tela.
Atualizei direto no banco na tabela: invoice_eletronic, campo: chave_nfe e deu certo!

Vou fazer outras para ver se o problema ocorre sempre ou se foi um caso isolado. Muito obrigado!

**Comment by eduardotd** [comment]
Gerei várias. Transmitiu e gerou a Danfe normalmente, Não consegui reproduzir o erro.

Tks!!
