### ISSUE TITLE
[11.0] Erro na Aplicação Cash Flow

### ISSUE THREAD

**Issue by nogueira-raphael** [Trust-Code/odoo-brasil#254]
Ao tentar gerar o fluxo de caixa o Odoo retorna o seguinte erro:

Odoo Server Error
Traceback (most recent call last):
File "/opt/odoo/odoo/http.py", line 646, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/opt/odoo/odoo/http.py", line 307, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
raise value
File "/opt/odoo/odoo/http.py", line 683, in dispatch
result = self._call_function(**self.params)
File "/opt/odoo/odoo/http.py", line 339, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
return f(dbname, *args, **kwargs)
File "/opt/odoo/odoo/http.py", line 332, in checked_call
result = self.endpoint(*a, **kw)
File "/opt/odoo/odoo/http.py", line 927, in call
return self.method(*args, **kw)
File "/opt/odoo/odoo/http.py", line 512, in response_wrap
response = f(*args, **kw)
File "/opt/odoo/addons/web/controllers/main.py", line 924, in call_button
action = self._call_kw(model, method, args, {})
File "/opt/odoo/addons/web/controllers/main.py", line 912, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/opt/odoo/odoo/api.py", line 689, in call_kw
return call_kw_multi(method, model, args, kwargs)
File "/opt/odoo/odoo/api.py", line 680, in call_kw_multi
result = method(recs, *args, **kwargs)
File "/opt/extra-addons/odoo-brasil/account_cash_flow/wizard/cash_flow.py", line 29, in button_calculate
return self.env['report'].get_action(
File "/opt/odoo/odoo/api.py", line 760, in getitem
return self.registry[model_name]._browse((), self)
File "/opt/odoo/odoo/modules/registry.py", line 177, in getitem
return self.models[model_name]
KeyError: 'report'

**Comment by nogueira-raphael** [comment]
O erro ocorre pois report não é mais um model.
Porém não sei uma forma para corrigir.

**Comment by danimaribeiro** [comment]
Fixed
