### ISSUE TITLE
Erro ao importar OFX

### ISSUE THREAD

**Issue by ghost** [Trust-Code/odoo-brasil#256]
Importo o primeiro arquivo OFX sem problemas, mais quando vou importar o proximo recebo a seguinte mesagem de erro:

Traceback (most recent call last):
  File "/opt/odoo/core/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/core/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/core/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/core/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/core/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/core/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/core/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/core/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/core/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/core/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/core/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/core/addons/account_bank_statement_import/account_bank_statement_import.py", line 51, in import_file
    statement_ids, notifications = self._create_bank_statements(stmts_vals)
  File "/opt/odoo/core/addons/account_bank_statement_import/account_bank_statement_import.py", line 226, in _create_bank_statements
    st_vals['balance_start'] += float(line_vals['amount'])
TypeError: unsupported operand type(s) for +=: 'Decimal' and 'float'

Alguma luz?

**Comment by ghost** [comment]
Notei que os dados contidos no cadastro da conta, como o digito, agencia, e titular da conta se desconfiguram após a primeira importação.
