### ISSUE TITLE
Erro ao gerar boleto banco do brasil

### ISSUE THREAD

**Issue by ghost** [Trust-Code/odoo-brasil#257]
Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1643, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1592, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/odoo/custom/addons/odoo-brasil/br_boleto/reports/report.py", line 43, in render_qweb_pdf
    pdf_string = Boleto.get_pdfs(boleto_list)
  File "/odoo/custom/addons/odoo-brasil/br_boleto/boleto/document.py", line 143, in get_pdfs
    boleto.drawBoleto(boleto_list[i])
  File "/usr/local/lib/python3.5/dist-packages/pyboleto/pdf.py", line 822, in drawBoleto
    d = self._drawReciboCaixa(boleto_dados, x, y)
  File "/usr/local/lib/python3.5/dist-packages/pyboleto/pdf.py", line 758, in _drawReciboCaixa
    boleto_dados.linha_digitavel
  File "/usr/local/lib/python3.5/dist-packages/pyboleto/data.py", line 437, in linha_digitavel
    linha = self.barcode
  File "/usr/local/lib/python3.5/dist-packages/pyboleto/data.py", line 209, in barcode
    len(value)))
ValueError: BoletoBB.campo_livre must have a length of 25, not '000000False00BNK1/2017/1817' (len: 27)

**Comment by ghost** [comment]
Resolvido, no Seq. do Nosso Número no prefixo deixar so o %(year)s/
