### ISSUE TITLE
[Resolvido] Erro ao emitir NFe no odoo 10 [no such child: nfeRetAutorizacaoLoteResult]

### ISSUE THREAD

**Issue by walterfrey** [Trust-Code/odoo-brasil#264]
Olá, Danimar, boa noite, tudo bem?

Estou tetando emitir uma NFe na versão 10, porém ele gera o seguinte erro:

```
Situação: -1 
Mensagem: no such child: nfeRetAutorizacaoLoteResult
Chave NFe:41171102985124000107550010000000011721216300
Protocolo Autorização:
```
Isso está ocorrendo quando clico em [Enviar Agora]
Não aparece nenhum anexo na fatura. Verifiquei a pasta que consta no config `data_dir = /home/odoo/.local/share/Odoo` porem não encontro o xml.

Por favor, você poderia me ajudar me dando um caminho?

Desde já muito obrigado.

Um abraço,

=================Detalhes do ambiente ================================
```
Traceback (most recent call last):
  File "/home/odoo/odoo-10.0/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-10.0/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-10.0/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-10.0/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-10.0/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo-10.0/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-10.0/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-10.0/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo-10.0/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo-10.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo-10.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/extras/odoo-brasil/br_nfe/models/invoice_eletronic.py", line 749, in action_send_eletronic_invoice
    retorno = resposta_recibo['object'].Body.\
  File "src/lxml/lxml.objectify.pyx", line 229, in lxml.objectify.ObjectifiedElement.__getattr__ (src/lxml/lxml.objectify.c:4146)
  File "src/lxml/lxml.objectify.pyx", line 450, in lxml.objectify._lookupChildOrRaise (src/lxml/lxml.objectify.c:7030)
AttributeError: no such child: nfeRetAutorizacaoLoteResult
```

**pip freeze**
```
asn1crypto==0.23.0
Babel==2.3.4
beautifulsoup4==4.6.0
boto==2.38.0
certifi==2017.7.27.1
cffi==1.11.2
chardet==2.3.0
colorama==0.3.2
cryptography==1.9
decorator==4.0.10
defusedxml==0.4.1
docutils==0.12
ebaysdk==2.1.4
eight==0.4.2
enum34==1.1.6
et-xmlfile==1.0.1
feedparser==5.2.1
funcsigs==1.0.2
future==0.16.0
gdata==2.0.18
gevent==1.1.2
greenlet==0.4.10
gyp==0.1
html5lib==0.999
idna==2.6
iotop==0.6
ipaddress==1.0.18
jcconv==0.2.3
jdcal==1.3
Jinja2==2.8
lxml==3.5.0
Mako==1.0.4
MarkupSafe==0.23
mock==2.0.0
OdooRPC==0.6.0
ofxparse==0.16
olefile==0.44
openpyxl==2.4.0b1
passlib==1.6.5
pbr==3.1.1
Pillow==3.4.1
ply==3.4
psutil==4.3.1
psycogreen==1.0
psycopg2==2.7.1
pycparser==2.10
pydot==1.2.3
Pygments==2.0.1
pyOpenSSL==17.3.0
pyparsing==2.1.10
pyPdf==1.13
pyserial==3.1.1
python-apt==0.9.3.12
python-boleto==0.3.5
Python-Chart==1.39
python-cnab==0.1.19
python-dateutil==2.5.3
python-debian==0.1.27
python-debianbts==1.11
python-ldap==2.4.27
python-openid==2.2.5
python-stdnum==1.7
PyTrustNFe==0.1.41
pytz==2016.7
pyusb==1.0.0
pyxmlsec==0.3.1
PyYAML==3.12
qrcode==5.3
reportbug==6.6.3
reportlab==3.3.0
requests==2.11.1
roman==2.0.0
setuptools-git==1.1
signxml==2.4.0
six==1.10.0
SOAPpy==0.12.22
suds==0.4
suds-jurko==0.6
suds-jurko-requests==1.2
suds-requests==0.3.1
urllib3==1.9.1
vatnumber==1.2
vobject==0.9.3
Werkzeug==0.9.6
wstools==0.4.3
xlrd==1.0.0
XlsxWriter==0.9.3
xlwt==1.1.2
```

**Comment by walterfrey** [comment]
Bom dia Galera, 

Problema resolvido.

A correção foi no PyTrustNfe, a classe `servidores.py` está com os endereços dos webservice do PR incompletos. o correto é:

```
UFPR = {
    NFE_AMBIENTE_PRODUCAO: {
        'servidor': 'nfe.fazenda.pr.gov.br',
        WS_NFE_INUTILIZACAO: 'nfe/NFeInutilizacao3?wsdl',
        WS_NFE_CONSULTA: 'nfe/NFeConsulta3?wsdl',
        WS_NFE_SITUACAO: 'nfe/NFeStatusServico3?wsdl',
        WS_NFE_CADASTRO: 'nfe/CadConsultaCadastro2?wsdl',
        WS_NFE_RECEPCAO_EVENTO: 'nfe/NFeRecepcaoEvento?wsdl',
        WS_NFE_CANCELAMENTO: 'nfe/NFeRecepcaoEvento?wsdl',
        WS_NFE_AUTORIZACAO: 'nfe/NFeAutorizacao?wsdl',
        WS_NFE_RET_AUTORIZACAO: 'nfe/NFeRetAutorizacao3?wsdl',
    },
    NFE_AMBIENTE_HOMOLOGACAO: {
        'servidor': 'homologacao.nfe.fazenda.pr.gov.br',
        WS_NFE_INUTILIZACAO: 'nfe/NFeInutilizacao3?wsdl',
        WS_NFE_CONSULTA: 'nfe/NFeConsulta3?wsdl',
        WS_NFE_SITUACAO: 'nfe/NFeStatusServico3?wsdl',
        WS_NFE_CADASTRO: 'nfe/CadConsultaCadastro2?wsdl',
        WS_NFE_RECEPCAO_EVENTO: 'nfe/NFeRecepcaoEvento?wsdl',
        WS_NFE_CANCELAMENTO: 'nfe/NFeRecepcaoEvento?wsdl',
        WS_NFE_AUTORIZACAO: 'nfe/NFeAutorizacao3?wsdl',
        WS_NFE_RET_AUTORIZACAO: 'nfe/NFeRetAutorizacao3?wsdl',
    }
}
```
E o nome da tag que a classe `invoice_eletronic.py` procura no objeto de retorno de NFeRetAutorizacao está incorreto:

```
retorno = resposta_recibo['object'].Body.\
                    nfeRetAutorizacaoLoteResult.retConsReciNFe
```

substitua: 

`retorno = resposta_recibo['object'].Body.nfeRetAutorizacaoResult.retConsReciNFe`

Isso emitindo em homologação nos webservices da receita do PR.

Valeu!
