### ISSUE TITLE
Erro Emissão NFE - UNICODE

### ISSUE THREAD

**Issue by carlos-korovsky** [Trust-Code/odoo-brasil#27]
Quando a empresa, no campo razão social, possuí um caractere & por exemplo, ocorre o seguinte erro:

Traceback (most recent call last):
  File "/opt/odoo10/odoo.git/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo10/odoo.git/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo10/odoo.git/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo10/odoo.git/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo10/odoo.git/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo10/odoo.git/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo10/odoo-brasil.git/br_nfse/models/invoice_eletronic.py", line 218, in action_send_eletronic_invoice
    super(InvoiceEletronic, self).action_send_eletronic_invoice()
  File "/opt/odoo10/odoo-brasil.git/br_nfe/models/invoice_eletronic.py", line 537, in action_send_eletronic_invoice
    resposta = autorizar_nfe(certificado, **lote)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/__init__.py", line 173, in autorizar_nfe
    return _send(certificado, 'NfeAutorizacao', True, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/__init__.py", line 119, in _send
    xmlElem_send = render_xml(path, '%s.xml' % method, True, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/xml/__init__.py", line 33, in render_xml
    root = etree.fromstring(xml, parser=parser)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79003)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118334)
  File "src/lxml/parser.pxi", line 1729, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:116892)
  File "src/lxml/parser.pxi", line 1063, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:110879)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
XMLSyntaxError: xmlParseEntityRef: no name, line 40, column 31 (line 40)

Substituindo o  & por um caractere e o problema não ocorre.

**Comment by danimaribeiro** [comment]
https://github.com/danimaribeiro/PyTrustNFe/pull/16
Versão 0.1.15 deve estar corrigido.
