### ISSUE TITLE
Erro ao enviar NFe - Odoo 11 Community

### ISSUE THREAD

**Issue by heinicken** [Trust-Code/odoo-brasil#271]
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/odoo-brasil/br_nfe/models/invoice_eletronic.py", line 816, in action_send_eletronic_invoice
    nfe_proc = gerar_nfeproc(resposta['sent_xml'], recibo_xml)
  File "/usr/local/lib/python3.5/dist-packages/pytrustnfe/utils.py", line 89, in gerar_nfeproc
    docRecibo = ET.fromstring(recibo)
  File "lxml.etree.pyx", line 3092, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70473)
  File "parser.pxi", line 1823, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106272)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

Mesmo atualizando todos os git's (trustcode modules & odoo-server) o erro continua. Estava com a versão 3.5.0 do lxml. Também testei com a versão 3.4.1 porém o mesmo problema. Alguém já enfrentou isso? Obrigado

**Comment by heinicken** [comment]
Só uma informação adicional. Quando fiz o teste usando o CFOP 6102 (intencionalmente para gerar erro de validação 732 com a SEFAZ) a comunicação obteve êxito e obtive o erro da SEFAZ (732 - CFOP de operação interestadual e idDest <> 2). 
Agora que mudei o CFOP para 5102 está gerando o erro acima (ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.)

**Comment by heinicken** [comment]
Mudei o conteúdo da variável recibo, linha 89, antes do call do etree no arquivo utils.py da lib pytrustnfe para:  
`<reciNFe version="1.0" encoding="utf-8"><...></reciNFe>`

Parece que o etree não aceita a estrutura antiga 

`<? xml  version="1.0" encoding="utf-8" ?><...>`

Fazendo essa alteração consegui emitir o DANFE e não obtive mais o erro de UNICODE e DECLARATION.

**Comment by crsilveira** [comment]
Também estou enfrentando o mesmo problema.

**Comment by rmlgti** [comment]
Tive o mesmo problema, resolvi atualizando o lxml e colocando a linha 89 dessa forma:
`docRecibo = ET.fromstring(recibo.encode('utf-8'))`
