### ISSUE TITLE
Erro a o gerar cnab Bradesco

### ISSUE THREAD

**Issue by carlsec** [Trust-Code/odoo-brasil#343]
Eae galera, estou com um problema aqui, to com o odoo 10 instalado no ubuntu com a localização da trustcode branch 10.0..porem a o gerar o cnab da um erro segue ele...

Odoo Server Error

Traceback (most recent call last):
  File "/home/coffee/odoo-10.0/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/coffee/odoo-10.0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/coffee/odoo-10.0/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/coffee/odoo-10.0/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/coffee/odoo-10.0/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/coffee/odoo-10.0/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/coffee/odoo-10.0/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/coffee/odoo-10.0/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/coffee/odoo-10.0/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/coffee/odoo-10.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/coffee/odoo-10.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/coffee/odoo-brasil-10.0/br_cnab/models/payment_order.py", line 56, in gerar_cnab
    remessa = cnab.remessa(order)
  File "/home/coffee/odoo-brasil-10.0/br_cnab/febraban/cnab_240/cnab_240.py", line 225, in remessa
    self.arquivo = Arquivo(self.bank, **header)
  File "/usr/local/lib/python2.7/dist-packages/cnab240/tipos.py", line 136, in __init__
    self.header = self.banco.registros.HeaderArquivo(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cnab240/registro.py", line 138, in __init__
    self.fromdict(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cnab240/registro.py", line 164, in fromdict
    setattr(self, key, value)
  File "/usr/local/lib/python2.7/dist-packages/cnab240/registro.py", line 98, in __set__
    self.valor = value
  File "/usr/local/lib/python2.7/dist-packages/cnab240/registro.py", line 31, in valor
    raise errors.TipoError(self, valor)
TipoError: campo:cedente_dv_ag_cc formato:alfa decimais:0 digitos:1 - valor:False

alguem consegue me da uma luz pfv

**Comment by crsilveira** [comment]
neste campo esta sendo passo valor Null (False) pra ele, coloque ZERO no Cadastro se não houver um DV da Agencia.

**Comment by carlsec** [comment]
Odoo Server Error

Traceback (most recent call last):
  File "/home/coffee/odoo-10.0/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/coffee/odoo-10.0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/coffee/odoo-10.0/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/coffee/odoo-10.0/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/coffee/odoo-10.0/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/coffee/odoo-10.0/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/coffee/odoo-10.0/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/coffee/odoo-10.0/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/coffee/odoo-10.0/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/coffee/odoo-10.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/coffee/odoo-10.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/coffee/odoo-brasil-10.0/br_cnab/models/payment_order.py", line 56, in gerar_cnab
    remessa = cnab.remessa(order)
  File "/home/coffee/odoo-brasil-10.0/br_cnab/febraban/cnab_240/cnab_240.py", line 225, in remessa
    self.arquivo = Arquivo(self.bank, **header)
  File "/usr/local/lib/python2.7/dist-packages/cnab240/tipos.py", line 136, in __init__
    self.header = self.banco.registros.HeaderArquivo(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cnab240/registro.py", line 138, in __init__
    self.fromdict(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cnab240/registro.py", line 164, in fromdict
    setattr(self, key, value)
  File "/usr/local/lib/python2.7/dist-packages/cnab240/registro.py", line 98, in __set__
    self.valor = value
  File "/usr/local/lib/python2.7/dist-packages/cnab240/registro.py", line 31, in valor
    raise errors.TipoError(self, valor)
TipoError: campo:cedente_convenio formato:alfa decimais:0 digitos:20 - valor:False

deu outro erro agora

 20 digitos ? o que seria esse cedente de convenio ? ainda estou aprendendo a usar o odoo e a primeira vez.

**Comment by carlsec** [comment]
consegui OBRIGADO.

faltava o codigo do beneficiario
