### ISSUE TITLE
Erro instalação dependencia PyTrustNFe

### ISSUE THREAD

**Issue by lucassilvab** [Trust-Code/odoo-brasil#348]
boa noite sou novato com o odoo estou fazendo alguns testes instalei a vertão 10.00 e quando vou instalar o PyTrustNFe retorna o seguinte erro

```
 Downloading PyTrustNFe-0.1.10.tar.gz
  Running setup.py (path:/tmp/pip_build_root/PyTrustNFe/setup.py) egg_info for package PyTrustNFe
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/PyTrustNFe/setup.py", line 4, in <module>
        long_description = open('README.md').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/PyTrustNFe/setup.py", line 4, in <module>

    long_description = open('README.md').read()

FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/PyTrustNFe
Storing debug log for failure in /home/lucas/.pip/pip.log
```

mas não grava o log tentei o outro passo

 git clone https://github.com/danimaribeiro/PyTrustNFe

Após entre na pasta
cd PyTrustNFe/

E instale com o comando:
python3 setup.py install

ele retornou

```
running install
Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing top-level names to PyTrustNFe3.egg-info/top_level.txt
writing PyTrustNFe3.egg-info/PKG-INFO
writing requirements to PyTrustNFe3.egg-info/requires.txt
writing dependency_links to PyTrustNFe3.egg-info/dependency_links.txt
writing manifest file 'PyTrustNFe3.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pytrustnfe
copying build/lib/pytrustnfe/client.py -> build/bdist.linux-x86_64/egg/pytrustnfe
copying build/lib/pytrustnfe/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe
copying build/lib/pytrustnfe/utils.py -> build/bdist.linux-x86_64/egg/pytrustnfe
creating build/bdist.linux-x86_64/egg/pytrustnfe/xml
copying build/lib/pytrustnfe/xml/filters.py -> build/bdist.linux-x86_64/egg/pytrustnfe/xml
copying build/lib/pytrustnfe/xml/validate.py -> build/bdist.linux-x86_64/egg/pytrustnfe/xml
copying build/lib/pytrustnfe/xml/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/xml
creating build/bdist.linux-x86_64/egg/pytrustnfe/xml/schemas
copying build/lib/pytrustnfe/xml/schemas/tiposBasico_v3.10.xsd -> build/bdist.linux-x86_64/egg/pytrustnfe/xml/schemas
copying build/lib/pytrustnfe/xml/schemas/xmldsig-core-schema_v1.01.xsd -> build/bdist.linux-x86_64/egg/pytrustnfe/xml/schemas
copying build/lib/pytrustnfe/xml/schemas/nfe_v3.10.xsd -> build/bdist.linux-x86_64/egg/pytrustnfe/xml/schemas
copying build/lib/pytrustnfe/xml/schemas/leiauteNFe_v3.10.xsd -> build/bdist.linux-x86_64/egg/pytrustnfe/xml/schemas
copying build/lib/pytrustnfe/xml/schemas/enviNFe_v3.10.xsd -> build/bdist.linux-x86_64/egg/pytrustnfe/xml/schemas
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfe
copying build/lib/pytrustnfe/nfe/assinatura.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe
copying build/lib/pytrustnfe/nfe/danfe.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfe/fonts
copying build/lib/pytrustnfe/nfe/fonts/NimbusSanL Regular.ttf -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe/fonts
copying build/lib/pytrustnfe/nfe/fonts/NimbusSanL Bold.ttf -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe/fonts
copying build/lib/pytrustnfe/nfe/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfe/templates
copying build/lib/pytrustnfe/nfe/templates/NfeConsultaCadastro.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe/templates
copying build/lib/pytrustnfe/nfe/templates/NfeAutorizacao.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe/templates
copying build/lib/pytrustnfe/nfe/templates/RecepcaoEventoManifesto.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe/templates
copying build/lib/pytrustnfe/nfe/templates/NfeStatusServico.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe/templates
copying build/lib/pytrustnfe/nfe/templates/NfeRetAutorizacao.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe/templates
copying build/lib/pytrustnfe/nfe/templates/NfeConsultaDest.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe/templates
copying build/lib/pytrustnfe/nfe/templates/RecepcaoEventoCancelamento.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe/templates
copying build/lib/pytrustnfe/nfe/templates/RecepcaoEventoEPEC.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe/templates
copying build/lib/pytrustnfe/nfe/templates/NfeConsultaProtocolo.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe/templates
copying build/lib/pytrustnfe/nfe/templates/RecepcaoEventoCarta.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe/templates
copying build/lib/pytrustnfe/nfe/templates/NFeDistribuicaoDFe.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe/templates
copying build/lib/pytrustnfe/nfe/templates/NfeInutilizacao.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe/templates
copying build/lib/pytrustnfe/nfe/comunicacao.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfe
copying build/lib/pytrustnfe/certificado.py -> build/bdist.linux-x86_64/egg/pytrustnfe
copying build/lib/pytrustnfe/Servidores.py -> build/bdist.linux-x86_64/egg/pytrustnfe
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse
copying build/lib/pytrustnfe/nfse/assinatura.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/issintel
copying build/lib/pytrustnfe/nfse/issintel/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/issintel
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/webiss
copying build/lib/pytrustnfe/nfse/webiss/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/webiss
copying build/lib/pytrustnfe/nfse/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/issnet
copying build/lib/pytrustnfe/nfse/issnet/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/issnet
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha
copying build/lib/pytrustnfe/nfse/betha/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha/templates
copying build/lib/pytrustnfe/nfse/betha/templates/Rps.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha/templates
copying build/lib/pytrustnfe/nfse/betha/templates/ConsultarLoteRps.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha/templates
copying build/lib/pytrustnfe/nfse/betha/templates/ConsultarNfseServicoPrestado.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha/templates
copying build/lib/pytrustnfe/nfse/betha/templates/ConsultarNfseFaixa.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha/templates
copying build/lib/pytrustnfe/nfse/betha/templates/ConsultarNfseServicoTomado.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha/templates
copying build/lib/pytrustnfe/nfse/betha/templates/SubstituirNfse.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha/templates
copying build/lib/pytrustnfe/nfse/betha/templates/CancelarNfse.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha/templates
copying build/lib/pytrustnfe/nfse/betha/templates/RecepcionarLoteRpsSincrono.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha/templates
copying build/lib/pytrustnfe/nfse/betha/templates/ConsultarNfsePorRps.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha/templates
copying build/lib/pytrustnfe/nfse/betha/templates/GerarNfse.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha/templates
copying build/lib/pytrustnfe/nfse/betha/templates/RecepcionarLoteRps.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha/templates
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/paulistana
copying build/lib/pytrustnfe/nfse/paulistana/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/paulistana
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/paulistana/templates
copying build/lib/pytrustnfe/nfse/paulistana/templates/ConsultaInformacoesLote.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/paulistana/templates
copying build/lib/pytrustnfe/nfse/paulistana/templates/EnvioLoteRPS.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/paulistana/templates
copying build/lib/pytrustnfe/nfse/paulistana/templates/ConsultaNFeEmitidas.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/paulistana/templates
copying build/lib/pytrustnfe/nfse/paulistana/templates/CancelamentoNFe.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/paulistana/templates
copying build/lib/pytrustnfe/nfse/paulistana/templates/EnvioRPS.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/paulistana/templates
copying build/lib/pytrustnfe/nfse/paulistana/templates/ConsultaLote.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/paulistana/templates
copying build/lib/pytrustnfe/nfse/paulistana/templates/ConsultaNFe.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/paulistana/templates
copying build/lib/pytrustnfe/nfse/paulistana/templates/ConsultaCNPJ.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/paulistana/templates
copying build/lib/pytrustnfe/nfse/paulistana/templates/ConsultaNFeRecebidas.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/paulistana/templates
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/susesu
copying build/lib/pytrustnfe/nfse/susesu/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/susesu
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/susesu/templates
copying build/lib/pytrustnfe/nfse/susesu/templates/EnviarNotaRetornaurlNota.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/susesu/templates
copying build/lib/pytrustnfe/nfse/susesu/templates/EnviarNota.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/susesu/templates
copying build/lib/pytrustnfe/nfse/susesu/templates/Nota.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/susesu/templates
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/dsf
copying build/lib/pytrustnfe/nfse/dsf/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/dsf
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/dsf/templates
copying build/lib/pytrustnfe/nfse/dsf/templates/consultarLote.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/dsf/templates
copying build/lib/pytrustnfe/nfse/dsf/templates/enviar.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/dsf/templates
copying build/lib/pytrustnfe/nfse/dsf/templates/cancelar.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/dsf/templates
copying build/lib/pytrustnfe/nfse/dsf/templates/consultarNFSeRps.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/dsf/templates
copying build/lib/pytrustnfe/nfse/dsf/templates/soap_header.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/dsf/templates
copying build/lib/pytrustnfe/nfse/dsf/templates/consulta_notas.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/dsf/templates
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/imperial
copying build/lib/pytrustnfe/nfse/imperial/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/imperial
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/imperial/templates
copying build/lib/pytrustnfe/nfse/imperial/templates/SoapRequest.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/imperial/templates
copying build/lib/pytrustnfe/nfse/imperial/templates/PROCESSARPS.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/imperial/templates
copying build/lib/pytrustnfe/nfse/imperial/templates/CANCELANOTAELETRONICA.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/imperial/templates
copying build/lib/pytrustnfe/nfse/imperial/templates/CONSULTANOTASPROTOCOLO.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/imperial/templates
copying build/lib/pytrustnfe/nfse/imperial/templates/CONSULTAPROTOCOLO.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/imperial/templates
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/simpliss
copying build/lib/pytrustnfe/nfse/simpliss/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/simpliss
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/simpliss/templates
copying build/lib/pytrustnfe/nfse/simpliss/templates/SoapRequest.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/simpliss/templates
copying build/lib/pytrustnfe/nfse/simpliss/templates/Rps.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/simpliss/templates
copying build/lib/pytrustnfe/nfse/simpliss/templates/ConsultarLoteRps.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/simpliss/templates
copying build/lib/pytrustnfe/nfse/simpliss/templates/ConsultarSituacaoLoteRps.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/simpliss/templates
copying build/lib/pytrustnfe/nfse/simpliss/templates/ConsultarNfse.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/simpliss/templates
copying build/lib/pytrustnfe/nfse/simpliss/templates/CancelarNfse.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/simpliss/templates
copying build/lib/pytrustnfe/nfse/simpliss/templates/ConsultarNfsePorRps.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/simpliss/templates
copying build/lib/pytrustnfe/nfse/simpliss/templates/GerarNfse.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/simpliss/templates
copying build/lib/pytrustnfe/nfse/simpliss/templates/RecepcionarLoteRps.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/simpliss/templates
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/ginfes
copying build/lib/pytrustnfe/nfse/ginfes/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/ginfes
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/ginfes/templates
copying build/lib/pytrustnfe/nfse/ginfes/templates/Rps.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/ginfes/templates
copying build/lib/pytrustnfe/nfse/ginfes/templates/ConsultarSituacaoLoteRpsV3.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/ginfes/templates
copying build/lib/pytrustnfe/nfse/ginfes/templates/CancelarNfseV3.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/ginfes/templates
copying build/lib/pytrustnfe/nfse/ginfes/templates/ConsultarNfseV3.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/ginfes/templates
copying build/lib/pytrustnfe/nfse/ginfes/templates/ConsultarLoteRpsV3.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/ginfes/templates
copying build/lib/pytrustnfe/nfse/ginfes/templates/ConsultarNfsePorRpsV3.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/ginfes/templates
copying build/lib/pytrustnfe/nfse/ginfes/templates/RecepcionarLoteRpsV3.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/ginfes/templates
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/floripa
copying build/lib/pytrustnfe/nfse/floripa/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/floripa
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/floripa/templates
copying build/lib/pytrustnfe/nfse/floripa/templates/cancelar_nota.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/floripa/templates
copying build/lib/pytrustnfe/nfse/floripa/templates/processar_nota.xml -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/floripa/templates
creating build/bdist.linux-x86_64/egg/pytrustnfe/nfse/saatri
copying build/lib/pytrustnfe/nfse/saatri/__init__.py -> build/bdist.linux-x86_64/egg/pytrustnfe/nfse/saatri
copying build/lib/pytrustnfe/exceptions.py -> build/bdist.linux-x86_64/egg/pytrustnfe
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/client.py to client.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/utils.py to utils.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/xml/filters.py to filters.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/xml/validate.py to validate.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/xml/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfe/assinatura.py to assinatura.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfe/danfe.py to danfe.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfe/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfe/comunicacao.py to comunicacao.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/certificado.py to certificado.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/Servidores.py to Servidores.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfse/assinatura.py to assinatura.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfse/issintel/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfse/webiss/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfse/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfse/issnet/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfse/betha/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfse/paulistana/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfse/susesu/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfse/dsf/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfse/imperial/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfse/simpliss/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfse/ginfes/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfse/floripa/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/nfse/saatri/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytrustnfe/exceptions.py to exceptions.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying PyTrustNFe3.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyTrustNFe3.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyTrustNFe3.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyTrustNFe3.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyTrustNFe3.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
pytrustnfe.xml.__pycache__.validate.cpython-34: module references __file__
pytrustnfe.nfe.__pycache__.danfe.cpython-34: module references __file__
pytrustnfe.nfe.__pycache__.__init__.cpython-34: module references __file__
pytrustnfe.nfse.betha.__pycache__.__init__.cpython-34: module references __file__
pytrustnfe.nfse.paulistana.__pycache__.__init__.cpython-34: module references __file__
pytrustnfe.nfse.susesu.__pycache__.__init__.cpython-34: module references __file__
pytrustnfe.nfse.dsf.__pycache__.__init__.cpython-34: module references __file__
pytrustnfe.nfse.imperial.__pycache__.__init__.cpython-34: module references __file__
pytrustnfe.nfse.simpliss.__pycache__.__init__.cpython-34: module references __file__
pytrustnfe.nfse.ginfes.__pycache__.__init__.cpython-34: module references __file__
pytrustnfe.nfse.floripa.__pycache__.__init__.cpython-34: module references __file__
creating 'dist/PyTrustNFe3-0.9.10-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing PyTrustNFe3-0.9.10-py3.4.egg
removing '/usr/local/lib/python3.4/dist-packages/PyTrustNFe3-0.9.10-py3.4.egg' (and everything under it)
creating /usr/local/lib/python3.4/dist-packages/PyTrustNFe3-0.9.10-py3.4.egg
Extracting PyTrustNFe3-0.9.10-py3.4.egg to /usr/local/lib/python3.4/dist-packages
PyTrustNFe3 0.9.10 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.4/dist-packages/PyTrustNFe3-0.9.10-py3.4.egg
Processing dependencies for PyTrustNFe3==0.9.10
Searching for cryptography>=1.8,<3
Reading https://pypi.python.org/simple/cryptography/
Best match: cryptography 2.1.4
Downloading https://pypi.python.org/packages/78/c5/7188f15a92413096c93053d5304718e1f6ba88b818357d05d19250ebff85/cryptography-2.1.4.tar.gz#md5=9f39d4d8f2b05f295fa0ff52475ec4f2
Processing cryptography-2.1.4.tar.gz
Writing /tmp/easy_install-rpcn1ie6/cryptography-2.1.4/setup.cfg
Running cryptography-2.1.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-rpcn1ie6/cryptography-2.1.4/egg-dist-tmp-1rucv1x4
Searching for cffi>=1.7
Reading https://pypi.python.org/simple/cffi/
Best match: cffi 1.11.5
Downloading https://pypi.python.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz#md5=ac8492f4ad952360737413e82d661908
Processing cffi-1.11.5.tar.gz
Writing /tmp/easy_install-rpcn1ie6/cryptography-2.1.4/temp/easy_install-ptq8np4j/cffi-1.11.5/setup.cfg
Running cffi-1.11.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-rpcn1ie6/cryptography-2.1.4/temp/easy_install-ptq8np4j/cffi-1.11.5/egg-dist-tmp-1pw9x_ns
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
compiling '_configtest.c':
__thread int some_threadlocal_variable_42;

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -c _configtest.c -o _configtest.o
success!
removing: _configtest.c _configtest.o
compiling '_configtest.c':
int main(void) { __sync_synchronize(); return 0; }

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -c _configtest.c -o _configtest.o
x86_64-linux-gnu-gcc -pthread _configtest.o -o _configtest
success!
removing: _configtest.c _configtest.o _configtest
c/_cffi_backend.c:15:17: fatal error: ffi.h: Arquivo ou diretório não encontrado
 #include <ffi.h>
                 ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1


```
estou com o unbunto 14.04 x64

desde ja grato.

**Comment by leovca** [comment]
Eu consegui assim:
pip3 install git+https://github.com/danimaribeiro/PyTrustNFe@master3

**Comment by danimaribeiro** [comment]
versão 10: "pip install pytrustnfe" - instalar signxml e dependencias antes.
versão 11: "pip3 install pytrustnfe3"  - instalar signxml e dependencias antes.
