### ISSUE TITLE
Emissão de nfe

### ISSUE THREAD

**Issue by lucassilvab** [Trust-Code/odoo-brasil#352]
Boa tarde pessoal quando vou emitir uma nfe da o seguinte erro

```
2018-03-02 20:08:30,637 31306 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/lucas/odoo/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/home/lucas/odoo/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/home/lucas/odoo/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/home/lucas/odoo/odoo/http.py", line 1313, in __call__
    self.load_addons()
  File "/home/lucas/odoo/odoo/http.py", line 1334, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/home/lucas/odoo/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/home/lucas/odoo-brasil/br_nfse/__init__.py", line 5, in <module>
    from . import models
  File "/home/lucas/odoo-brasil/br_nfse/models/__init__.py", line 7, in <module>
    from . import invoice_eletronic
  File "/home/lucas/odoo-brasil/br_nfse/models/invoice_eletronic.py", line 17, in <module>
    from pytrustnfe.nfse.paulistana import envio_lote_rps
  File "/usr/local/lib/python2.7/dist-packages/PyTrustNFe3-0.9.10-py2.7.egg/pytrustnfe/nfse/paulistana/__init__.py", line 12, in <module>
    from pytrustnfe.nfse.assinatura import Assinatura
  File "/usr/local/lib/python2.7/dist-packages/PyTrustNFe3-0.9.10-py2.7.egg/pytrustnfe/nfse/assinatura.py", line 9, in <module>
    consts = xmlsec.constants
AttributeError: 'module' object has no attribute 'constants'

```

alguem poderia me ajudar?

**Comment by crsilveira** [comment]
Reinstale a xmlsec  ... 
  http://labs.libre-entreprise.org/frs/download.php/897/pyxmlsec-0.3.1.tar.gz

**Comment by lucassilvab** [comment]
executei pip install http://labs.libre-entreprise.org/frs/download.php/897/pyxmlsec-0.3.1.tar.gz

continua com o mesmo erro.

**Comment by danimaribeiro** [comment]
O pytrustnfe3 é para python 3 e não 2.
Use o pytrustnfe.

**Comment by lucassilvab** [comment]
boa noite @danimaribeiro  obrigado aparentemente agora estou com um problema na cripto da senha do certificado.

retorna
```
Traceback (most recent call last):
  File "/home/lucas/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/lucas/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/lucas/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/lucas/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/lucas/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/lucas/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/lucas/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/lucas/odoo/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/lucas/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/lucas/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/lucas/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/lucas/odoo-brasil/br_nfse/models/nfse_imperial.py", line 198, in action_send_eletronic_invoice
    super(InvoiceEletronic, self).action_send_eletronic_invoice()
  File "/home/lucas/odoo-brasil/br_nfse/models/nfse_ginfes.py", line 223, in action_send_eletronic_invoice
    super(InvoiceEletronic, self).action_send_eletronic_invoice()
  File "/home/lucas/odoo-brasil/br_nfse/models/nfse_simpliss.py", line 188, in action_send_eletronic_invoice
    super(InvoiceEletronic, self).action_send_eletronic_invoice()
  File "/home/lucas/odoo-brasil/br_nfse/models/nfse_susesu.py", line 195, in action_send_eletronic_invoice
    super(InvoiceEletronic, self).action_send_eletronic_invoice()
  File "/home/lucas/odoo-brasil/br_nfse/models/invoice_eletronic.py", line 247, in action_send_eletronic_invoice
    super(InvoiceEletronic, self).action_send_eletronic_invoice()
  File "/home/lucas/odoo-brasil/br_nfe/models/invoice_eletronic.py", line 751, in action_send_eletronic_invoice
    resposta = autorizar_nfe(certificado, **lote)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/__init__.py", line 199, in autorizar_nfe
    return _send(certificado, 'NfeAutorizacao', True, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/__init__.py", line 156, in _send
    xmlElem_send, kwargs['NFes'][0]['infNFe']['Id'])
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/assinatura.py", line 18, in assina_xml
    cert, key = extract_cert_and_key_from_pfx(self.arquivo, self.senha)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/certificado.py", line 24, in extract_cert_and_key_from_pfx
    pfx = crypto.load_pkcs12(pfx, password)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 2223, in load_pkcs12
    parse_result = _lib.PKCS12_parse(p12, passphrase, pkey, cert, cacerts)
TypeError: initializer for ctype 'char *' must be a str or list or tuple, not unicode
```

pode me ajudar?

**Comment by lucassilvab** [comment]
alguem poderia me auxiliar?
