### ISSUE TITLE
Erro na ação de enviar nfe

### ISSUE THREAD

**Issue by alysonbg** [Trust-Code/odoo-brasil#370]
2018-03-14 17:55:56,016 6479 ERROR odoo-prod odoo.addons.base.ir.ir_cron: Call from cron Cron Enviar NFe for server action #298 failed in Job #6
Traceback (most recent call last):
  File "/home/vagrant/odoo-brasil/br_account_einvoice/models/invoice_eletronic.py", line 446, in cron_send_nfe
    item.action_send_eletronic_invoice()
  File "/home/vagrant/odoo-brasil/br_nfe/models/invoice_eletronic.py", line 777, in action_send_eletronic_invoice
    modelo=self.model)
  File "/usr/local/lib/python3.5/dist-packages/pytrustnfe/nfe/__init__.py", line 210, in autorizar_nfe
    return _send(certificado, 'NfeAutorizacao', **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pytrustnfe/nfe/__init__.py", line 194, in _send
    send_raw=send_raw)
  File "/usr/local/lib/python3.5/dist-packages/pytrustnfe/nfe/comunicacao.py", line 34, in executar_consulta
    return sanitize_response(xml_retorno.encode())
  File "/usr/local/lib/python3.5/dist-packages/pytrustnfe/xml/__init__.py", line 61, in sanitize_response
    tree = etree.fromstring(response)
  File "src/lxml/etree.pyx", line 3212, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1126, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 600, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 710, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 639, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and body, line 1, column 1110

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/odoo/odoo/tools/safe_eval.py", line 348, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/vagrant/odoo-brasil/br_account_einvoice/models/invoice_eletronic.py", line 448, in cron_send_nfe
    item.log_exception(e)
  File "/home/vagrant/odoo-brasil/br_account_einvoice/models/invoice_eletronic.py", line 433, in log_exception
    self.mensagem_retorno = exc.message
AttributeError: 'XMLSyntaxError' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/odoo/odoo/addons/base/ir/ir_cron.py", line 101, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/home/vagrant/odoo/odoo/addons/base/ir/ir_actions.py", line 541, in run
    res = func(action, eval_context=eval_context)
  File "/home/vagrant/odoo/odoo/addons/base/ir/ir_actions.py", line 417, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/vagrant/odoo/odoo/tools/safe_eval.py", line 371, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/vagrant/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/vagrant/odoo/odoo/tools/safe_eval.py", line 348, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/vagrant/odoo-brasil/br_account_einvoice/models/invoice_eletronic.py", line 448, in cron_send_nfe
    item.log_exception(e)
  File "/home/vagrant/odoo-brasil/br_account_einvoice/models/invoice_eletronic.py", line 433, in log_exception
    self.mensagem_retorno = exc.message
ValueError: <class 'AttributeError'>: "'XMLSyntaxError' object has no attribute 'message'" while evaluating
'model.cron_send_nfe()'

Esse erro acontece toda vez que tentamos emitir uma nfe. Alguma sugestão de como resolver? Cidade é Fortaleza.

**Comment by danimaribeiro** [comment]
Fixed.
