### ISSUE TITLE
Erro emissão nfe

### ISSUE THREAD

**Issue by lucassilvab** [Trust-Code/odoo-brasil#401]
Bom dia quando vou emitir uma NFe esta retornando o seguinte erro.
Situação: -1
Mensagem: initializer for ctype 'char *' must be a str or list or tuple, not unicode
Chave NFe:35180323238113000125550010000000061460161442
Protocolo Autorização:

alguem poderia me auxilizar?

**Comment by lucassilvab** [comment]
Alguem?

**Comment by danimaribeiro** [comment]
Versão?

**Comment by lucassilvab** [comment]
10

**Comment by danimaribeiro** [comment]
Os dados do certificado estão corretos?

**Comment by lucassilvab** [comment]
Aparentemente tudo ok.

**Comment by lucassilvab** [comment]
Traceback (most recent call last):
  File "/home/lucas/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/lucas/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/lucas/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/lucas/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/lucas/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/lucas/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/lucas/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/lucas/odoo/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/lucas/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/lucas/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/lucas/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/lucas/odoo-brasil/br_nfse/models/nfse_imperial.py", line 198, in action_send_eletronic_invoice
    super(InvoiceEletronic, self).action_send_eletronic_invoice()
  File "/home/lucas/odoo-brasil/br_nfse/models/nfse_ginfes.py", line 223, in action_send_eletronic_invoice
    super(InvoiceEletronic, self).action_send_eletronic_invoice()
  File "/home/lucas/odoo-brasil/br_nfse/models/nfse_simpliss.py", line 188, in action_send_eletronic_invoice
    super(InvoiceEletronic, self).action_send_eletronic_invoice()
  File "/home/lucas/odoo-brasil/br_nfse/models/nfse_susesu.py", line 195, in action_send_eletronic_invoice
    super(InvoiceEletronic, self).action_send_eletronic_invoice()
  File "/home/lucas/odoo-brasil/br_nfse/models/invoice_eletronic.py", line 247, in action_send_eletronic_invoice
    super(InvoiceEletronic, self).action_send_eletronic_invoice()
  File "/home/lucas/odoo-brasil/br_nfe/models/invoice_eletronic.py", line 751, in action_send_eletronic_invoice
    resposta = autorizar_nfe(certificado, **lote)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/__init__.py", line 199, in autorizar_nfe
    return _send(certificado, 'NfeAutorizacao', True, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/__init__.py", line 156, in _send
    xmlElem_send, kwargs['NFes'][0]['infNFe']['Id'])
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/assinatura.py", line 18, in assina_xml
    cert, key = extract_cert_and_key_from_pfx(self.arquivo, self.senha)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/certificado.py", line 24, in extract_cert_and_key_from_pfx
    pfx = crypto.load_pkcs12(pfx, password)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 2223, in load_pkcs12
    parse_result = _lib.PKCS12_parse(p12, passphrase, pkey, cert, cacerts)
TypeError: initializer for ctype 'char *' must be a str or list or tuple, not unicode

**Comment by ghost** [comment]
Boa noite

Alguém poderia me ajudar? Instalei o Odoo 13 mais não consigo baixar e nem usar para emissão de MDF ?
