### ISSUE TITLE
Erro ao imprimir Danfe 

### ISSUE THREAD

**Issue by wspimentel** [Trust-Code/odoo-brasil#414]
Olá!

- Primeiramente parabéns pelo projeto!
- Estou realizando um fluxo utilizando odoo-brasil com a contabilidade brasileira. 
- Consegui executar todo o fluxo e gerar uma NFe em homologação. Entretanto mesmo com a chave gerada não consigo imprimir a NFe.
- Será se ficou faltando instalar algum aplicativo?

Debug Gerado:

Traceback (most recent call last):
  File "/usr/lib/python3.5/base64.py", line 518, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'NoneType'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/root/odoo/addons/web/controllers/main.py", line 1600, in report_download
  File "/root/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/root/odoo/addons/web/controllers/main.py", line 1549, in report_routes
    html = report.with_context(context).render_qweb_html(docids, data=data)[0]
  File "/root/odoo-brasil/br_nfe/reports/danfe_report.py", line 28, in render_qweb_pdf
  File "/usr/lib/python3.5/base64.py", line 560, in decodestring
    return decodebytes(s)
  File "/usr/lib/python3.5/base64.py", line 552, in decodebytes
    _input_type_check(s)
  File "/usr/lib/python3.5/base64.py", line 521, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not NoneType

**Comment by wspimentel** [comment]
Olá! Consegui resolver o problema.

Servidor Ubuntu

**Faça o download do arquivo deb para a biblioteca wkhtmltopdf**
sudo wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb

**Baixe a biblioteca Libpng12**
wget http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb

**Instale a biblioteca Libpng12**
sudo dpkg -i libpng12-0_1.2.54-1ubuntu1_amd64.deb

**Instale agora o arquivo wkhtmltopdf deb**
sudo dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb

**Copie os arquivos para os seguintes locais**
sudo cp /usr/local/bin/wkhtmltopdf /usr/bin
sudo cp /usr/local/bin/wkhtmltoimage /usr/bin

**Utilize os comandos para reinicializar o Odoo 11**

service odoo restart
ou
./odoo-bin --config=odoo-config

**Comment by clanslive** [comment]
Bom dia, procedi como descrito acima pois estou com erro semelhante ao imprimir a DANFE, mas não obtive sucesso.

Descrição do erro.

Traceback (most recent call last):
  File "/usr/lib/python3.5/base64.py", line 518, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/addons/web/controllers/main.py", line 1600, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/opt/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1549, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo/odoo-brasil/br_nfe/reports/danfe_report.py", line 28, in render_qweb_pdf
    nfe_xml = base64.decodestring(nfe.nfe_processada)
  File "/usr/lib/python3.5/base64.py", line 560, in decodestring
    return decodebytes(s)
  File "/usr/lib/python3.5/base64.py", line 552, in decodebytes
    _input_type_check(s)
  File "/usr/lib/python3.5/base64.py", line 521, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not NoneType

Obs: até o presente momento estou com a situação: 230
Rejeicao: IE do emitente nao cadastrada, pois estou aguardando liberação do orgão responsavel do meu Estado.

**Comment by wspimentel** [comment]
- Forneça todos os parâmetros e veja se consegue gerar. 
- Não esqueça de reinicializar o Odoo.
- No meu caso cadastrei todas as informação e consegui gera o pdf normalmente após esse roteiro.
- Após todos os procedimentos gere uma nova nota fiscal.

**Comment by clanslive** [comment]
Resolvido, no meu caso depois que  a empresa foi habilitada para emissão de NFE consegui imprimir a DANFE.

muito obrigado pela atenção.
