### ISSUE TITLE
Erro ao instalar Conta a Pagar e Receber ou Boleto

### ISSUE THREAD

**Issue by andercrist** [Trust-Code/odoo-brasil#417]
Boa tarde pessoal, estou recorrendo a vocês pois já tentei de várias vezes encontrar o problema e não achei, toda vez que tento instalar o Contas a Pagar e Receber no Odoo 10 acontece esse erro. Ou **KeyError: 'payment_method_ok'**

Traceback (most recent call last):
  File "/opt/odoo10/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo10/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo10/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo10/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo10/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo10/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo10/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo10/odoo/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo10/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo10/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo10/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo10/odoo/odoo/addons/base/module/module.py", line 411, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo10/odoo/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo10/odoo/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo10/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo10/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo10/odoo/odoo/modules/loading.py", line 135, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "/opt/odoo10/odoo/odoo/modules/registry.py", line 295, in setup_models
    model._setup_fields(partial)
  File "/opt/odoo10/odoo/odoo/models.py", line 2842, in _setup_fields
    field.setup_full(self)
  File "/opt/odoo10/odoo/odoo/fields.py", line 502, in setup_full
    self._setup_related_full(model)
  File "/opt/odoo10/odoo/odoo/fields.py", line 539, in _setup_related_full
    field = target._fields[name]
**KeyError: 'payment_method_id'**

**Comment by danimaribeiro** [comment]
Esse campo não existe na localização.
O problema não tem a ver com os nossos módulos.
