### ISSUE TITLE
Erro na Impressão de DANFE

### ISSUE THREAD

**Issue by gglimass** [Trust-Code/odoo-brasil#422]
uso o debian linux 9 stretch, odoo 11. instalei o wkhtmltopdf com o procedimento baixo e consigo imprimir os orçamento e tudo mais , exceto a NFE, que mostra o erro mais abaixo.
wget https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
tar xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
cp /wkhtmltox/bin/wkhtmlto*   /usr/bin/

Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3.5/base64.py", line 518, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1603, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1552, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo/addons/odoo-brasil/br_nfe/reports/danfe_report.py", line 29, in render_qweb_pdf
    nfe_xml = base64.decodestring(nfe.nfe_processada)
  File "/usr/lib/python3.5/base64.py", line 560, in decodestring
    return decodebytes(s)
  File "/usr/lib/python3.5/base64.py", line 552, in decodebytes
    _input_type_check(s)
  File "/usr/lib/python3.5/base64.py", line 521, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not NoneType

**Comment by wspimentel** [comment]
Então tive o mesmo problema, no meu casso consegui resolver com esse procedimento 
https://github.com/Trust-Code/odoo-brasil/issues/414

**Comment by gglimass** [comment]
Amigo qual versão do linux você usa? no ubuntu e Debian stretch a bliblioteca libpng12 não instala por incompatibilidade com o SSL. 
Não acredito que seja problema com o wkhtmltopdf, pois instalei uma versão compatível, e todos os outros relatórios funcionam normalmente.

**Comment by gglimass** [comment]
solucionado.. na verdade a nota não poderia ser impressa devido ter dado erro na sefaz...diferente do odoo 8 que podia-se ver a nota fiscal mesmo antes de enviar.
