### ISSUE TITLE
Problema ao gerar boleto sicoob

### ISSUE THREAD

**Issue by lucassilvab** [Trust-Code/odoo-brasil#426]
quando vou gerar o boleto do sicoob gera o seguinte erro

Traceback (most recent call last):
  File "/home/uplife/odoo/addons/web/controllers/main.py", line 1611, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/home/uplife/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/uplife/odoo/addons/web/controllers/main.py", line 1560, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/home/uplife/odoo-brasil/br_boleto/reports/report.py", line 44, in render_qweb_pdf
    pdf_string = Boleto.get_pdfs(boleto_list)
  File "/home/uplife/odoo-brasil/br_boleto/boleto/document.py", line 148, in get_pdfs
    boleto.drawBoleto(boleto_list[i])
  File "/usr/local/lib/python3.5/dist-packages/pyboleto/pdf.py", line 822, in drawBoleto
    d = self._drawReciboCaixa(boleto_dados, x, y)
  File "/usr/local/lib/python3.5/dist-packages/pyboleto/pdf.py", line 674, in _drawReciboCaixa
    boleto_dados.format_nosso_numero()
  File "/usr/local/lib/python3.5/dist-packages/pyboleto/bank/sicoob.py", line 50, in format_nosso_numero
    self.dv_nosso_numero)
  File "/usr/local/lib/python3.5/dist-packages/pyboleto/bank/sicoob.py", line 40, in dv_nosso_numero
    soma += int(composto[i]) * int(constante[i])
ValueError: invalid literal for int() with base 10: 'B'

ja cadastrei o sequencial dos numeros e os dados de configuração do boleto

**Comment by danimaribeiro** [comment]
A sequência do nosso número não deve conter letras.
