### ISSUE TITLE
Validação de NFE - após instalação do ginfes

### ISSUE THREAD

**Issue by gglimass** [Trust-Code/odoo-brasil#428]
A validação da NFE da erro após a instalação do module Ginfes 
Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_invoice.py", line 779, in action_invoice_open
    return to_open_invoices.invoice_validate()
  File "/opt/odoo/addons/odoo-brasil/br_account_einvoice/models/account_invoice.py", line 229, in invoice_validate
    edoc_vals = self._prepare_edoc_vals(item, inv_lines)
  File "/opt/odoo/addons/odoo-brasil/br_nfse/models/account_invoice.py", line 33, in _prepare_edoc_vals
    res['numero'] = inv.service_serie_id.internal_sequence_id.next_by_id()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_sequence.py", line 263, in next_by_id
    return self._next()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_sequence.py", line 249, in _next
    return self._next_do()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_sequence.py", line 189, in _next_do
    number_next = _update_nogap(self, self.number_increment)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_sequence.py", line 52, in _update_nogap
    self._cr.execute("SELECT number_next FROM %s WHERE id=%s FOR UPDATE NOWAIT" % (self._table, self.id))
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: ERRO:  operador não existe: integer = boolean
LINHA 1: SELECT number_next FROM ir_sequence WHERE id=False FOR UPDAT...
                                                     ^
DICA:  Nenhum operador corresponde com o nome e o(s) tipo(s) de argumento(s) informados. Você precisa adicionar conversões de tipo explícitas.

**Comment by beliajevas** [comment]
Olá gglimass.
Você conseguiu resolver este problema?
Se sim poderia me informar como?

**Comment by gglimass** [comment]
Não resolvi! 
Eu removi todos os módulos que faziam referência a nota de serviço e voltou a funcionar.

**Comment by beliajevas** [comment]
Mas você não utiliza a emissão de nfe no Oddo?

**Comment by gglimass** [comment]
Emito NFE . O ginfes esta relacionado a nota fiscal de serviços.
não conseguir emitir a nota de serviço, tentei alguns procedimentos que não deram certo.
Desinstalei o Ginfes e continuei usando NFE.

**Comment by beliajevas** [comment]
Perfeito. Vou continuar a pesquisas e testar e quando descobrir eu posto aqui.

**Comment by beliajevas** [comment]
Alguém com o mesmo problema?

**Comment by luiz-alonso-zz** [comment]
**Estou com o problema bem parecido !**

Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 837, in convert_xml_import
    etree.parse(os.path.join(config['root_path'],'import_xml.rng' )))
  File "src/lxml/etree.pyx", line 3426, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1840, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 651, in lxml.etree._raiseParseError
  File "b'/usr/lib/python3/dist-packages/odoo/import_xml.rng'", line 0
lxml.etree.XMLSyntaxError: <no detail available>

Este erro ocorre quando tento instalar qualquer aplicação da pasta odoo-brasil, o demais aplicativos também padrão também são afetados. Até então achei que fosse alguma dependência do python3 más está tudo atualizados dentro dos conformes.
COMANDO = pip3 freeze

appdirs==1.4.3
asn1crypto==0.24.0
atomicwrites==1.1.5
attrs==18.1.0
Babel==2.4.0
beautifulsoup4==4.6.0
Brlapi==0.6.7
cached-property==1.4.3
certifi==2018.4.16
chardet==3.0.4
chrome-gnome-shell==0.0.0
coverage==4.5.1
coveralls==1.3.0
cryptography==2.3
cupshelpers==1.0
Cython==0.28.5
decorator==4.3.0
defusedxml==0.5.0
docopt==0.6.2
docutils==0.14
eight==0.4.2
entrypoints==0.2.3.post2
feedparser==5.2.1
future==0.16.0
gevent==1.3.5
greenlet==0.4.13
Guake==3.3.0
html2text==2018.1.9
html5lib==1.0.1
httplib2==0.9.2
idna==2.6
isodate==0.6.0
Jinja2==2.10
keyring==13.1.0
keyrings.alt==3.0
louis==3.6.0
lxml==4.2.4
Mako==1.0.7
MarkupSafe==1.0
mock==2.0.0
more-itertools==4.3.0
odoo==11.0.post20180808
ofxparse==0.16
olefile==0.45.1
passlib==1.7.1
pbr==3.1.1
pexpect==4.6.0
Pillow==5.2.0
pkgconfig==1.3.1
pluggy==0.7.1
psutil==5.4.6
psycopg2==2.7.5
py==1.5.4
pybase64==0.4.0
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0.1
pydot==1.2.4
Pygments==2.2.0
pygobject==3.28.2
pyinotify==0.9.6
pyOpenSSL==17.5.0
pyparsing==2.2.0
PyPDF2==1.26.0
pyserial==3.4
pysmbc==1.0.15.6
pytest==3.7.1
pytest-cov==2.5.1
python-apt==1.6.2
python-dateutil==2.6.1
python-debian==0.1.32
python-debianbts==2.7.2
python-stdnum==1.9
python3-boleto==1.0.3
python3-cnab==1.0.3
PyTrustNFe3==1.0.0
pytz==2018.5
pyusb==1.0.0
pyxdg==0.25
PyYAML==3.12
reportbug==7.5.0
reportlab==3.5.2
requests==2.18.4
requests-toolbelt==0.8.0
roman==2.0.0
scour==0.37
SecretStorage==2.3.1
setuptools-git==1.1
signxml==2.5.2
six==1.11.0
suds-jurko==0.7.dev0
suds-jurko-requests==1.2
unattended-upgrades==0.1
urllib3==1.22
vatnumber==1.2
webencodings==0.5
Werkzeug==0.14.1
XlsxWriter==0.9.6
xlwt==1.3.0
xmlsec==1.3.3
zeep==3.0.0

não sei mais o que pode ser, extrai os arquivos odoo-brasil-11.0 na raiz da pasta addons 

este é meu odoo.conf 

[options]
; This is the password that allows database operations:
; admin_passwd = admin
db_host = False
db_port = False
db_user = odoo
db_password = False
;addons_path = /usr/lib/python3/dist-packages/odoo/addons

Obrigado a todos

**Comment by luiz-alonso-zz** [comment]
Olá a todos
 
Bem consegui resolver o problema, más não tenho certeza se realmente foi este procedimento que deu certo, parece que e erro esta nas dependências instaladas no meu python3 verifiquei o arquivo requeriments.txt e observeis as versão exigidas, percebi que as minhas estava com uma versão superior, então removi todas a dependências listadas no arquivo e instalei as versão exigidas, após finalizar este procedimento, tive alguns outros problemas com meu banco de dados, as vendas lanças estavam dando erro, "acho que é devido a atualização dos módulos odoo-brasil", então desinstalei todos os módulos da pasta odoo-brasil dentro do odoo e instalei novamente e quase tudo voltou ao normal, exceto as minhas definições fiscais na qual eu havia definido, ma sem dor de cabeça também.

OBSERVAÇÂO: Este procedimento deu certo para mim, eu não sou programador e nem usuário avançado em linux, deve existir algum caminho mais fácil com uma explicação mais técnica sobre o assunto más espero que ajude aquele que deseje tentar.

**Comment by beliajevas** [comment]
Alguém achou a causa do problema na emissão de nfs?

**Comment by danimaribeiro** [comment]
Fixed.
