### ISSUE TITLE
Erro Odoo Server Error

### ISSUE THREAD

**Issue by TecSecret** [Trust-Code/odoo-brasil#46]
Após instalar a localização brasil (odoo-brasil) aqui constantes os módulos que aparecem como "Produzidos Por Odoo S.A" não instalam mais reportam o erro

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1192, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3810, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3900, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)

Alguém sabe como resolver?? 

Utilizo ubuntu server.

Abraços

**Comment by danimaribeiro** [comment]
Tem a mensagem de erro?
Você postou apenas o stack trace.

**Comment by TecSecret** [comment]
Bom dia Danimar,

Isso que você desejava?
________________________________
ParseError: "duplicate key value violates unique constraint "account_tax_template_name_company_uniq"
DETAIL:  Key (name, company_id, type_tax_use)=(IPI Sa\xedda 3%, 1, sale) already exists.
" while parsing /usr/lib/python2.7/dist-packages/odoo/addons/l10n_br/data/account_tax_template_data.xml:699, near
<record id="tax_template_out_ipi3" model="account.tax.template">
			<field name="description">IPI 3%</field>
			<field name="name">IPI Sa&#237;da 3%</field>
			<field name="amount">3</field>
			<field name="type_tax_use">sale</field>
			<field ref="account_template_201010301" name="account_id"/>
			<field ref="account_template_101050502" name="refund_account_id"/>
			<field eval="0" name="price_include"/>
			<field eval="0" name="tax_discount"/>
			<field ref="l10n_br_account_chart_template" name="chart_template_id"/>
			<field name="tag_ids" eval="[(6,0,[ref('tag_br_24'), ref('tag_br_23')])]"/>
       	</record>

**Comment by danimaribeiro** [comment]
Isto.
Não deve ser instalado nenhum módulo l10n_br*, os mesmos não são compatíveis.
