### ISSUE TITLE
Erro ao enviar boleto via email

### ISSUE THREAD

**Issue by thiago95macedo** [Trust-Code/odoo-brasil#481]
Traceback (most recent call last):
  File "/opt/adaxtechnology/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/adaxtechnology/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/adaxtechnology/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/adaxtechnology/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/adaxtechnology/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/adaxtechnology/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/adaxtechnology/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/adaxtechnology/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/adaxtechnology/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/adaxtechnology/modulos/interface/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/adaxtechnology/modulos/interface/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/adaxtechnology/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/adaxtechnology/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/adaxtechnology/modulos/contabil/br_boleto/wizard/send_boleto_email.py", line 16, in send_boletos_by_email
    invoices.send_email_boleto_queue()
  File "/opt/adaxtechnology/modulos/contabil/br_boleto/models/account_invoice.py", line 27, in send_email_boleto_queue
    boleto, fmt = self.env['ir.actions.report'].render_report(
AttributeError: 'ir.actions.report' object has no attribute 'render_report'

**Comment by danimaribeiro** [comment]
Fixed #534
