### ISSUE TITLE
Erro envio NF-e

### ISSUE THREAD

**Issue by paulafernanda** [Trust-Code/odoo-brasil#512]
Instalei o Oddo 10, com a atualização para a Nf-e 4.0, e ao enviar a nota está aparecendo essa mensagem.

Traceback (most recent call last):
  File "/home/wecast10/odoo/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/wecast10/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/wecast10/odoo/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/wecast10/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/wecast10/odoo/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/wecast10/odoo/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/home/wecast10/odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/home/wecast10/odoo/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/wecast10/odoo/addons/web/controllers/main.py", line 884, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/wecast10/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/wecast10/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/wecast10/odoo-brasil/br_nfe/models/invoice_eletronic.py", line 771, in action_send_eletronic_invoice
    if retorno.cStat == 103:
  File "src/lxml/objectify.pyx", line 230, in lxml.objectify.ObjectifiedElement.__getattr__
  File "src/lxml/objectify.pyx", line 450, in lxml.objectify._lookupChildOrRaise
AttributeError: no such child: cStat

**Comment by pauloneda** [comment]
Dá uma olhada nesta Issue

#463

**Comment by danimaribeiro** [comment]
Atualizar a lib pytrusnfe resolve o problema.
