### ISSUE TITLE
BUG - Contratos Recorrentes (OCA) / Modos de Pagamento / br_boleto

### ISSUE THREAD

**Issue by thiago95macedo** [Trust-Code/odoo-brasil#555]
As funções de modo de pagamento está apresentando problemas quando se está usando os módulos de Gestão de Contratos da OCA juntamente com o contract_payment_mode e o modulo br_boleto
Após vários teste alterando a ordem de instalação dos módulos envolvidos me deparei com erros que não permitiam a instalação e ate mesmo a parada do sistema causando problemas na db.

Senário:
Emisao de boleto -instalado
Contrato recorrente - instalado

Ao tentar instalar o contract_payment_mode para definir a modo de pagamento no contrato de recorrencia recebi o seguinte erro:
______________________________

The operation can not be completed, probably due to the following factors:

deletion: you may be trying to delete a record while other records still refer to it
creation / update: a required field is not configured correctly
[object with reference: Payment methods - account.payment.mode]
______________________________

Em uma base de teste deixei o modulo de boleto para ser instalado por ultimo, e o mesmo nao instala.
_______________________
Traceback (most recent call last):
  File "/opt/adax-erp/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/adax-erp/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/adax-erp/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/adax-erp/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/adax-erp/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/adax-erp/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/adax-erp/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/adax-erp/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/adax-erp/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/adax-erp/modulos/interface/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/adax-erp/modulos/interface/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/adax-erp/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/adax-erp/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/opt/adax-erp/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/adax-erp/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/adax-erp/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/adax-erp/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/adax-erp/odoo/modules/loading.py", line 371, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/adax-erp/odoo/modules/loading.py", line 265, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/adax-erp/odoo/modules/loading.py", line 143, in load_module_graph
    registry.setup_models(cr)
  File "/opt/adax-erp/odoo/modules/registry.py", line 279, in setup_models
    model._setup_fields()
  File "/opt/adax-erp/odoo/models.py", line 2425, in _setup_fields
    field.setup_full(self)
  File "/opt/adax-erp/odoo/fields.py", line 471, in setup_full
    self._setup_related_full(model)
  File "/opt/adax-erp/odoo/fields.py", line 508, in _setup_related_full
    field = target._fields[name]
KeyError: 'payment_method_id'
_______________________

**Comment by danimaribeiro** [comment]
Acredito que os dois não funcionam juntamente.

**Comment by nogueira-raphael** [comment]
Foi mencionado neste issue #365
