### ISSUE TITLE
Odoo 11 - Erro ao criar a Fatura

### ISSUE THREAD

**Issue by Daniel-Furcht** [Trust-Code/odoo-brasil#587]
Após atualizar o Odoo 11 hoje, não é mais possível emitir a fatura, sendo gerado o seguinte erro:
Erro:

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f2ebf658630>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f2ebf658630>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/sale/wizard/sale_make_invoice_advance.py", line 134, in create_invoices
    sale_orders.action_invoice_create(final=True)
  File "/opt/odoo/odoo/addons/sale/models/sale.py", line 430, in action_invoice_create
    line.invoice_line_create(invoices[group_key].id, line.qty_to_invoice)
  File "/opt/odoo/odoo/addons/sale/models/sale.py", line 1005, in invoice_line_create
    invoice_lines |= self.env['account.invoice.line'].create(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3372, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo/odoo/models.py", line 3529, in _create
    self.recompute()
  File "/opt/odoo/odoo/odoo/models.py", line 4904, in recompute
    vals = {n: rec[n] for n in ns}
  File "/opt/odoo/odoo/odoo/models.py", line 4904, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/opt/odoo/odoo/odoo/models.py", line 4758, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/opt/odoo/odoo/odoo/fields.py", line 1028, in determine_value
    self.compute_value(recs)
  File "/opt/odoo/odoo/odoo/fields.py", line 1008, in compute_value
    self._compute_value(records)
  File "/opt/odoo/odoo/odoo/fields.py", line 1001, in _compute_value
    self.compute(records)
  File "/opt/odoo/odoo/odoo/fields.py", line 586, in _compute_related
    values = [first(value[name]) for value in values]
  File "/opt/odoo/odoo/odoo/fields.py", line 586, in <listcomp>
    values = [first(value[name]) for value in values]
  File "/opt/odoo/odoo/odoo/models.py", line 4758, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/opt/odoo/odoo/odoo/fields.py", line 1042, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo/odoo/odoo/models.py", line 2646, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/opt/odoo/odoo/odoo/models.py", line 2590, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/odoo/odoo/models.py", line 2709, in _read_from_database
    cr.execute(query_str, params)
  File "/opt/odoo/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column account_invoice_line.fiscal_position_type does not exist
LINE 1: ...e"."company_fiscal_type" as "company_fiscal_type","account_i...
                                                             ^

**Comment by danimaribeiro** [comment]
Atualize sua base.
