### ISSUE TITLE
Erro na geração de carta de correção

### ISSUE THREAD

**Issue by carlos-korovsky** [Trust-Code/odoo-brasil#61]
Quando é gerada uma carta de correção ocorre o seguinte erro:
```
Traceback (most recent call last):
  File "/opt/odoo10/odoo.git/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo10/odoo.git/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo10/odoo.git/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo10/odoo.git/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo10/odoo.git/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo10/odoo.git/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo10/odoo-brasil.git/br_nfe/wizard/carta_correcao_eletronica.py", line 83, in send_letter
    'message': retorno.retEvento.infEvento.xEvento,
  File "src/lxml/lxml.objectify.pyx", line 229, in lxml.objectify.ObjectifiedElement.__getattr__ (src/lxml/lxml.objectify.c:3837)
  File "src/lxml/lxml.objectify.pyx", line 450, in lxml.objectify._lookupChildOrRaise (src/lxml/lxml.objectify.c:6541)
AttributeError: no such child: xEvento
```
Foi utilizado o seguinte texto na carta: `Código EAN: 6935364051426`

Aparentemente o erro ocorre na recepção da resposta. Quando tenta-se enviar novamente, o SEFAZ retorna: `573 - Rejeicao: Duplicidade de Evento` indicando que a carta de correção foi transmitida corretamente.

Versões dos pacotes instalados:
PyTrustNFe (0.1.18) - PyTrustNFe é uma biblioteca para envio de NF-e
INSTALLED: 0.1.18 (latest)
Repositórios odoo.git e odoo-brasil.git atualizados em 06/01/2017 às 13:00

**Comment by danimaribeiro** [comment]
Qual o estado que está testando?

**Comment by carlos-korovsky** [comment]
Santa Catarina

**Comment by danimaribeiro** [comment]
Fixed https://github.com/Trust-Code/odoo-brasil/pull/67
