### ISSUE TITLE
Erro durante o envio da NFSe-Ginfes V11.0

### ISSUE THREAD

**Issue by marcelsavegnago** [Trust-Code/odoo-brasil#625]
Caros,

Durante o envio da NFSe Ginfes estou recebendo o seguinte erro:

> Traceback (most recent call last):
>   File "/opt/odoo11/odoo/odoo/http.py", line 650, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo11/odoo/odoo/http.py", line 310, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/opt/odoo11/odoo/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/opt/odoo11/odoo/odoo/http.py", line 692, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/odoo11/odoo/odoo/http.py", line 342, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/odoo11/odoo/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/odoo11/odoo/odoo/http.py", line 335, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/odoo11/odoo/odoo/http.py", line 936, in __call__
>     return self.method(*args, **kw)
>   File "/opt/odoo11/odoo/odoo/http.py", line 515, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo11/odoo/addons/web/controllers/main.py", line 938, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/opt/odoo11/odoo/addons/web/controllers/main.py", line 926, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/odoo11/odoo/odoo/api.py", line 689, in call_kw
>     return call_kw_multi(method, model, args, kwargs)
>   File "/opt/odoo11/odoo/odoo/api.py", line 680, in call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "/opt/odoo11/custom/odoo-brasil/br_nfse_ginfes/models/invoice_eletronic.py", line 255, in action_send_eletronic_invoice
>     certificado, xml=xml_to_send, ambiente=self.ambiente)
>   File "/usr/local/lib/python3.5/dist-packages/pytrustnfe/nfse/ginfes/__init__.py", line 68, in recepcionar_lote_rps
>     return _send(certificado, 'RecepcionarLoteRpsV3', **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/pytrustnfe/nfse/ginfes/__init__.py", line 53, in _send
>     response, obj = sanitize_response(response.encode('utf-8'))
>   File "/usr/local/lib/python3.5/dist-packages/pytrustnfe/xml/__init__.py", line 49, in sanitize_response
>     tree = etree.fromstring(response.encode('UTF-8'), parser=parser)
> AttributeError: 'bytes' object has no attribute 'encode'

**Comment by marcelsavegnago** [comment]
Problema resolvido. Atualizei o módulo PyTrustNFe para a versão 1.0.19 e está rodando corretamente.
