### ISSUE TITLE
Erro emissão NFE com transportadora

### ISSUE THREAD

**Issue by carlos-korovsky** [Trust-Code/odoo-brasil#68]
Ao emitir uma nota fiscal, quando seleciona-se uma transportadora, ocorre o seguinte erro na geração do xml:
```
Traceback (most recent call last):
  File "/opt/odoo10/odoo.git/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo10/odoo.git/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo10/odoo.git/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo10/odoo.git/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo10/odoo.git/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo10/odoo.git/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo10/odoo.git/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo10/odoo-brasil.git/br_nfe/models/invoice_eletronic.py", line 640, in action_send_eletronic_invoice
    resposta = autorizar_nfe(certificado, **lote)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/__init__.py", line 177, in autorizar_nfe
    return _send(certificado, 'NfeAutorizacao', True, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/nfe/__init__.py", line 123, in _send
    xmlElem_send = render_xml(path, '%s.xml' % method, True, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pytrustnfe/xml/__init__.py", line 33, in render_xml
    root = etree.fromstring(xml, parser=parser)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:77737)
  File "src/lxml/parser.pxi", line 1830, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:116674)
  File "src/lxml/parser.pxi", line 1711, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:115220)
  File "src/lxml/parser.pxi", line 1051, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:109345)
  File "src/lxml/parser.pxi", line 584, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:103584)
  File "src/lxml/parser.pxi", line 694, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:105238)
  File "src/lxml/parser.pxi", line 624, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:104147)
XMLSyntaxError: xmlParseEntityRef: no name, line 248, column 35
```
Se não for especificada uma transportadora a nota é emitida corretamente.
Também reparei que os campos de peso não são armazenados como ponto flutuante, apenas inteiro.
A nota foi configurada como 
  - Modalidade do frete: 0 - Emitente
  - Peso bruto: 1,5
  - Peso liquido: 1,4
  - Nº Volumes: 1
  - Espécie: Caixa
  - Marca: Genérica
  - Numeração: 100

A nota foi emitida para o estado de Santa Catarina, venda dentro do estado.
Versões:
  - Odoo e brasil-odoo atualizados em: 2017-01-07
  - PyTrustNfe: 0.1.19

Observação: Módulo br_delivery não instalado.

**Comment by danimaribeiro** [comment]
O nome da transportadora tem "&" na razão social?

**Comment by carlos-korovsky** [comment]
Acabei de verificar, tem sim.

**Comment by danimaribeiro** [comment]
Corrigido https://github.com/danimaribeiro/PyTrustNFe/pull/23
