### ISSUE TITLE
Erro ao atualizar br_boleto

### ISSUE THREAD

**Issue by ghost** [Trust-Code/odoo-brasil#726]
Erro:
Aviso

Traceback (most recent call last):
  File "/opt/adax-erp/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/opt/adax-erp/odoo/addons/base/ir/ir_ui_view.py", line 335, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/adax-erp/odoo/addons/base/ir/ir_ui_view.py", line 1042, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/adax-erp/odoo/addons/base/ir/ir_ui_view.py", line 503, in raise_view_error
    raise ValueError(message)
ValueError: O campo `l10n_br_pymt_interest_account_id` não existe

Contexto de erro:
Veja `res_config_settings.email.boleto`
[view_id: 1162, xml_id: n/a, model: res.config.settings, parent_id: 744]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/adax-erp/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/adax-erp/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/adax-erp/odoo/addons/base/ir/ir_model.py", line 1487, in _update
    record = record.create(values)
  File "/opt/adax-erp/odoo/addons/base/ir/ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/adax-erp/odoo/models.py", line 3381, in create
    self._fields[key].determine_inverse(record)
  File "/opt/adax-erp/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/adax-erp/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/opt/adax-erp/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/adax-erp/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/opt/adax-erp/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/opt/adax-erp/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nO campo `l10n_br_pymt_interest_account_id` não existe\n\nContexto de erro:\nVeja `res_config_settings.email.boleto`\n[view_id: 1162, xml_id: n/a, model: res.config.settings, parent_id: 744]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/adax-erp/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/adax-erp/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/adax-erp/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/adax-erp/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/adax-erp/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/adax-erp/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/adax-erp/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/adax-erp/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/adax-erp/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/adax-erp/modulos/interface/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/adax-erp/modulos/interface/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/adax-erp/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/adax-erp/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/opt/adax-erp/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/adax-erp/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/adax-erp/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/adax-erp/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/adax-erp/odoo/modules/loading.py", line 371, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/adax-erp/odoo/modules/loading.py", line 265, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/adax-erp/odoo/modules/loading.py", line 172, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/adax-erp/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/adax-erp/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/adax-erp/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/adax-erp/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/opt/adax-erp/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/adax-erp/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/adax-erp/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/adax-erp/odoo/addons/base/ir/ir_model.py", line 1487, in _update
    record = record.create(values)
  File "/opt/adax-erp/odoo/addons/base/ir/ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/adax-erp/odoo/models.py", line 3381, in create
    self._fields[key].determine_inverse(record)
  File "/opt/adax-erp/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/adax-erp/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/opt/adax-erp/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/adax-erp/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/opt/adax-erp/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/opt/adax-erp/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

O campo `l10n_br_pymt_interest_account_id` não existe

Contexto de erro:
Veja `res_config_settings.email.boleto`
[view_id: 1162, xml_id: n/a, model: res.config.settings, parent_id: 744]
None" while parsing /opt/adax-erp/modulos/localbr/br_boleto/views/res_config_settings.xml:3, near
<record id="res_config_settings_email_boleto" model="ir.ui.view">
        <field name="name">res_config_settings.email.boleto</field>
        <field name="model">res.config.settings</field>
        <field name="inherit_id" ref="br_account.account_config_settings_email_templates"/>
        <field name="arch" type="xml">
            <div id="mail_templates" position="inside">
                <div id="mail_template_boleto" class="col-xs-12 col-md-6 o_setting_box">
                    <div class="o_setting_left_pane"/>
                    <div class="o_setting_right_pane">
                        <label for="boleto_email_tmpl" string="Modelo de e-mail envio boleto"/>
                        <span class="fa fa-lg fa-building-o" title="Values set here are company-specific."/>
                        <div class="text-muted">
                            Modelo a ser utilizado no envio de boleto automatizado
                        </div>
                        <div class="content-group">
                            <div class="row mt16">
                                <label for="boleto_email_tmpl" string="Modelo" class="col-md-3 o_light_label"/>
                                <field name="boleto_email_tmpl"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </field>
    </record>

**Comment by ghost** [comment]
Atualização do modulo ``br_account_payment`` necessário
