### ISSUE TITLE
A ultima versão do odoo Branche 11.0

### ISSUE THREAD

**Issue by ImplantiSolucoes** [Trust-Code/odoo-brasil#836]
O campo `legal_name` não existe

Contexto de erro:
Veja `br_base.partner.filter`
view_id: 199, xml_id: br_base.view_br_base_partner_filter, model: res.partner, parent_id: 114
None" while parsing /opt/odoo/modulos/localbr/br_base/views/res_partner_view.xml:5, near
<record id="view_br_base_partner_filter" model="ir.ui.view">
        <field name="name">br_base.partner.filter</field>
        <field name="model">res.partner</field>
        <field name="inherit_id" ref="base.view_res_partner_filter"/>
        <field name="arch" type="xml">
            <field name="name" position="after">
                <field name="legal_name"/>
                <field name="cnpj_cpf"/>
            </field>
        </field>
    </record>

**Comment by ImplantiSolucoes** [comment]
2019-06-18 14:24:18,879 3619 ERROR felipe werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/core/odoo/service/server.py", line 319, in app
    return self.app(e, s)
  File "/opt/odoo/core/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/core/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/core/odoo/http.py", line 1321, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/core/odoo/http.py", line 1476, in dispatch
    odoo.registry(db).check_signaling()
  File "/opt/odoo/core/odoo/__init__.py", line 76, in registry
    return modules.registry.Registry(database_name)
  File "/opt/odoo/core/odoo/modules/registry.py", line 61, in __new__
    return cls.new(db_name)
  File "/opt/odoo/core/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/core/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/core/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/core/odoo/modules/loading.py", line 146, in load_module_graph
    model_names = registry.load(cr, package)
  File "/opt/odoo/core/odoo/modules/registry.py", line 250, in load
    model = cls._build_model(self, cr)
  File "/opt/odoo/core/odoo/models.py", line 428, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'product.fiscal.classification' does not exist in registry.
