### ISSUE TITLE
Falha ao processar carrinho de compras

### ISSUE THREAD

**Issue by marcos-mendez** [Trust-Code/odoo-brasil#878]
Server Error:
We are not able to redirect you to the payment form. unorderable types: str() > int()

Exception during JSON request handling.
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/http.py", line 653, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
raise value
File "/usr/lib/python3/dist-packages/odoo/http.py", line 695, in dispatch
result = self._call_function(**self.params)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
return f(dbname, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
result = self.endpoint(*a, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in call
return self.method(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/controllers/main.py", line 859, in payment_transaction
return tx.render_sale_button(order, '/shop/payment/validate')
File "/usr/lib/python3/dist-packages/odoo/addons/sale_payment/models/payment.py", line 214, in render_sale_button
values=values,
File "/usr/lib/python3/dist-packages/odoo/addons/payment/models/payment_acquirer.py", line 429, in render
values = method(values)
File "/usr/lib/python3/dist-packages/odoo/custom-addons/br_payment_cielo/models/cielo.py", line 74, in cielo_form_generate_values
if (order.partner_id.street2) > 0:
TypeError: unorderable types: str() > int()

**Comment by danimaribeiro** [comment]
Teu código não está atualizado

Linha 74 do arquivo cielo.py.
https://github.com/Trust-Code/odoo-brasil/blob/11.0/br_payment_cielo/models/cielo.py#L74
