### ISSUE TITLE
Erro relatório fluxo de caixa (account_cash_flow)

### ISSUE THREAD

**Issue by Melodivo** [Trust-Code/odoo-brasil#879]
Bom dia
Estou usando a versão 12 - Trustcode
Este erro ocorre quando tento gerar um fluxo de caixa.
Alguém pode me ajudar?
antecipo agradecimentos.

Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/home/elc/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/elc/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/elc/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/elc/odoo12/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/elc/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/elc/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/elc/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/elc/odoo12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/elc/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/elc/odoo12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/elc/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/elc/odoo12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/elc/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/elc/odoo12/odoo-brasil/account_cash_flow/wizard/cash_flow.py", line 27, in button_calculate
    cashflow_id.action_calculate_report()
  File "/home/elc/odoo12/odoo-brasil/account_cash_flow/models/cash_flow_report.py", line 219, in action_calculate_report
    move_lines.sort (key=lambda x: datetime.datetime.strptime (x['date'], '%Y-%m-%d'))
  File "/home/elc/odoo12/odoo-brasil/account_cash_flow/models/cash_flow_report.py", line 219, in <lambda>
    move_lines.sort (key=lambda x: datetime.datetime.strptime (x['date'], '%Y-%m-%d'))
TypeError: strptime() argument 1 must be str, not datetime.date

**Comment by Melodivo** [comment]
Resolvido. Após reinstalação o erro mudou, e foi postado no GoogleGroups-OdooBrasil onde foi dada a solução.
Grato.
Melodivo

**Comment by dsolucoes** [comment]
@Melodivo  Bom dia.
Após a reinstalação do módulo?

**Comment by Melodivo** [comment]
Boa noite,
Não entendi a pergunta.


Em ter., 7 de jan. de 2020 às 09:35, Dalth TI <notifications@github.com>
escreveu:
