### ISSUE TITLE
View `br_account.invoice.line.form` não possui o campo 'state'.

### ISSUE THREAD

**Issue by aledr** [Trust-Code/odoo-brasil#903]
Segue problema ao tentar atualizar a base na atual revisão da branch 12.0.

```
2019-10-15 22:51:52,265 19282 ERROR odoo_12_hmg odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/odoo_12/odoo/modules/registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "/home/odoo/odoo_12/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/odoo_12/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'odoo_12_hmg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo_12/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/home/odoo/odoo_12/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/home/odoo/odoo_12/odoo/addons/base/models/ir_ui_view.py", line 1119, in postprocess_and_fields
    self.raise_view_error("\n".join(msg_lines), view_id)
  File "/home/odoo/odoo_12/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Field 'state' used in attributes must be present in view but is missing:
 - 'state' in attrs="{'required': [('state', '=', 'transmitido')]}"

Error context:
View `br_account.invoice.line.form`
[view_id: 1077, xml_id: br_stock_account.view_br_account_invoice_line_form, model: account.invoice.line, parent_i
d: 751]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo_12/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/odoo_12/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/odoo/odoo_12/odoo/models.py", line 3841, in _load_records
    data['record']._load_records_write(data['values'])
  File "/home/odoo/odoo_12/addons/website/models/ir_ui_view.py", line 121, in _load_records_write
    super(View, self)._load_records_write(values)
  File "/home/odoo/odoo_12/odoo/models.py", line 3779, in _load_records_write
    self.write(values)
  File "/home/odoo/odoo_12/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/home/odoo/odoo_12/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo/odoo_12/odoo/models.py", line 3350, in write
    fields[0].determine_inverse(records)
  File "/home/odoo/odoo_12/odoo/fields.py", line 1125, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/odoo_12/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/odoo/odoo_12/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/home/odoo/odoo_12/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo/odoo_12/odoo/models.py", line 3324, in write
    self._write(store_vals)
  File "/home/odoo/odoo_12/odoo/models.py", line 3460, in _write
    self._validate_fields(vals)
  File "/home/odoo/odoo_12/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nField \'state\' used in attributes must b
e present in view but is missing:\n - \'state\' in attrs="{\'required\': [(\'state\', \'=\', \'transmitido\')]}"\
n\nError context:\nView `br_account.invoice.line.form`\n[view_id: 1077, xml_id: br_stock_account.view_br_account_
invoice_line_form, model: account.invoice.line, parent_id: 751]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo_12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo_12/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/odoo_12/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/odoo_12/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/odoo/odoo_12/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/odoo_12/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/odoo_12/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/odoo_12/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/home/odoo/odoo_12/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/odoo_12/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/odoo_12/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/odoo/odoo_12/odoo/models.py", line 3841, in _load_records
    data['record']._load_records_write(data['values'])
  File "/home/odoo/odoo_12/addons/website/models/ir_ui_view.py", line 121, in _load_records_write
    super(View, self)._load_records_write(values)
  File "/home/odoo/odoo_12/odoo/models.py", line 3779, in _load_records_write
    self.write(values)
  File "/home/odoo/odoo_12/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/home/odoo/odoo_12/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo/odoo_12/odoo/models.py", line 3350, in write
    fields[0].determine_inverse(records)
  File "/home/odoo/odoo_12/odoo/fields.py", line 1125, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/odoo_12/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/odoo/odoo_12/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/home/odoo/odoo_12/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo/odoo_12/odoo/models.py", line 3324, in write
    self._write(store_vals)
  File "/home/odoo/odoo_12/odoo/models.py", line 3460, in _write
    self._validate_fields(vals)
  File "/home/odoo/odoo_12/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Field 'state' used in attributes must be present in view but is missing:
 - 'state' in attrs="{'required': [('state', '=', 'transmitido')]}"

Error context:
View `br_account.invoice.line.form`
[view_id: 1077, xml_id: br_stock_account.view_br_account_invoice_line_form, model: account.invoice.line, parent_i
d: 751]
None" while parsing /home/odoo/odoo-brasil_12/br_stock_account/views/account_invoice.xml:103, near
<record model="ir.ui.view" id="view_br_account_invoice_line_form">
        <field name="name">br_account.invoice.line.form</field>
        <field name="model">account.invoice.line</field>
        <field name="inherit_id" ref="br_account.view_br_account_invoice_line_form"/>
        <field name="priority">36</field>
        <field name="arch" type="xml">
            <field name="price_subtotal" position="after">
                <field name="valor_frete" attrs="{'invisible': [('product_type', '=', 'service')]}"/>
                <field name="valor_seguro" attrs="{'invisible': [('product_type', '=', 'service')]}"/>
                <field name="outras_despesas" attrs="{'invisible': [('product_type', '=', 'service')]}"/>
            </field>
        </field>
```

**Comment by danimaribeiro** [comment]
Atualizar o módulo br_nfse e posteriormente o módulo br_account.
