### ISSUE TITLE
erro Gerenciar direitos de acesso

### ISSUE THREAD

**Issue by abrunos** [Trust-Code/odoo-brasil#951]
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo12/odoo12-server/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo12-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo12-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo12-server/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo12-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo12-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo12-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo12-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo12-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo12-server/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo12/odoo12-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo12-server/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo12/odoo12-server/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo12/odoo12-server/odoo/models.py", line 1376, in load_views
    for [v_id, v_type] in views
  File "/opt/odoo12/odoo12-server/odoo/models.py", line 1376, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/odoo12/odoo12-server/odoo/models.py", line 1462, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/opt/odoo12/odoo12-server/odoo/addons/base/models/ir_ui_view.py", line 1096, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/odoo12/odoo12-server/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: O campo `employee_id` não existe

Contexto de erro:
Veja `res.users.form`
[view_id: 144, xml_id: base.view_users_form, model: res.users, parent_id: n/a]

**Comment by abrunos** [comment]
erro ao acessar Gerenciar direitos de acesso. alguma atualização corrige esse erro?

**Comment by danimaribeiro** [comment]
Quais os passos para reproduzir o problema?
