### ISSUE TITLE
Erro Element '{http://www.portalfiscal.inf.br/nfe}ide': Missing child element(s). Expected is ( {http://www.portalfiscal.inf.br/nfe}verProc )

### ISSUE THREAD

**Issue by katiakweb** [Trust-Code/odoo-brasil#952]
Alguém sabe me explicar porque estou recebendo este erro quando vou validar a NFe?

**Comment by jonatasartur** [comment]
O XML da NFe foi [alterado](https://github.com/danimaribeiro/PyTrustNFe/commit/a9154ba93d683933bf47e5fdf8cac87eb0bc3c47#diff-37b859cefa81b7c2a9ea0dae900d2478R30) para pegar a versão da NFe do módulo [odoo-brasil/br_nfe](https://github.com/Trust-Code/odoo-brasil/blob/12.0/br_nfe/models/invoice_eletronic.py#L478) ao invés do [PyTrustNFe](https://github.com/danimaribeiro/PyTrustNFe/blob/master3/pytrustnfe/nfe/templates/NfeAutorizacao.xml#L30)
Recomendo atualizar seus módulos da [Trust-Code/odoo-brasil](https://github.com/Trust-Code/odoo-brasil) e o [PyTrustNFe](https://github.com/danimaribeiro/PyTrustNFe)
Ou se quiser, pode atualizar só o módulo [br_nfe](https://github.com/Trust-Code/odoo-brasil/tree/12.0/br_nfe) que talvez resolva.

**Comment by katiakweb** [comment]
> O XML da NFe foi [alterado](https://github.com/danimaribeiro/PyTrustNFe/commit/a9154ba93d683933bf47e5fdf8cac87eb0bc3c47#diff-37b859cefa81b7c2a9ea0dae900d2478R30) para pegar a versão da NFe do módulo [odoo-brasil/br_nfe](https://github.com/Trust-Code/odoo-brasil/blob/12.0/br_nfe/models/invoice_eletronic.py#L478) ao invés do [PyTrustNFe](https://github.com/danimaribeiro/PyTrustNFe/blob/master3/pytrustnfe/nfe/templates/NfeAutorizacao.xml#L30)
> Recomendo atualizar seus módulos da [Trust-Code/odoo-brasil](https://github.com/Trust-Code/odoo-brasil) e o [PyTrustNFe](https://github.com/danimaribeiro/PyTrustNFe)
> Ou se quiser, pode atualizar só o módulo [br_nfe](https://github.com/Trust-Code/odoo-brasil/tree/12.0/br_nfe) que talvez resolva.

Ok, vou fazer isso e testar novamente. Sabe me dizer qual versão do PYTrustNFe devo usar? Estou usando o Odoo v12.

**Comment by jonatasartur** [comment]
> > O XML da NFe foi [alterado](https://github.com/danimaribeiro/PyTrustNFe/commit/a9154ba93d683933bf47e5fdf8cac87eb0bc3c47#diff-37b859cefa81b7c2a9ea0dae900d2478R30) para pegar a versão da NFe do módulo [odoo-brasil/br_nfe](https://github.com/Trust-Code/odoo-brasil/blob/12.0/br_nfe/models/invoice_eletronic.py#L478) ao invés do [PyTrustNFe](https://github.com/danimaribeiro/PyTrustNFe/blob/master3/pytrustnfe/nfe/templates/NfeAutorizacao.xml#L30)
> > Recomendo atualizar seus módulos da [Trust-Code/odoo-brasil](https://github.com/Trust-Code/odoo-brasil) e o [PyTrustNFe](https://github.com/danimaribeiro/PyTrustNFe)
> > Ou se quiser, pode atualizar só o módulo [br_nfe](https://github.com/Trust-Code/odoo-brasil/tree/12.0/br_nfe) que talvez resolva.
> 
> Ok, vou fazer isso e testar novamente. Sabe me dizer qual versão do PYTrustNFe devo usar? Estou usando o Odoo v12.

Atualize os módulos da TrustCode e PyTrustNFe para alguma versão depois de Outubro de 2019.

**Comment by katiakweb** [comment]
Fiz a atualização do conforme sugerido e agora o erro mudou... 

Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/sale/models/account_invoice.py", line 59, in action_invoice_open
    res = super(AccountInvoice, self).action_invoice_open()
  File "/opt/odoo/odoo-server/addons/account/models/account_invoice.py", line 959, in action_invoice_open
    return to_open_invoices.invoice_validate()
  File "/opt/odoo/custom/addons/odoo-brasil/br_boleto/models/account_invoice.py", line 60, in invoice_validate
    res = super(AccountInvoice, self).invoice_validate()
  File "/opt/odoo/custom/addons/sale_commission/models/account_invoice.py", line 35, in invoice_validate
    return super(AccountInvoice, self).invoice_validate()
  File "/opt/odoo/custom/addons/odoo-brasil/br_account_einvoice/models/account_invoice.py", line 255, in invoice_validate
    item, inv_lines, item.product_serie_id)
  File "/opt/odoo/custom/addons/odoo-brasil/br_nfe/models/account_invoice.py", line 92, in _prepare_edoc_vals
    inv, inv_lines, serie_id)
  File "/opt/odoo/custom/addons/odoo-brasil/br_stock_account/models/account_invoice.py", line 79, in _prepare_edoc_vals
    inv, inv_lines, serie_id)
  File "/opt/odoo/custom/addons/odoo-brasil/br_account_einvoice/models/account_invoice.py", line 234, in _prepare_edoc_vals
    self._prepare_edoc_item_vals(inv_line)))
  File "/opt/odoo/custom/addons/odoo-brasil/br_nfe/models/account_invoice.py", line 220, in _prepare_edoc_item_vals
    vals['icms_substituto'] = invoice_line.icms_substituto or 0.0
AttributeError: 'account.invoice.line' object has no attribute 'icms_substituto'

Alguma outra ideia?

**Comment by danimaribeiro** [comment]
Acho que você não baixou todos os módulos corretamente.
Precisa só baixar a última versão.
Para quem não está acostumado com desenvolvimento de software, é extremamente essencial fixar as versões que se está utilizando. Quando for atualizar, atualizar todas dependências juntamente.

**Comment by danimaribeiro** [comment]
O seu problema é apenas de código desatualizado.
Fechando.
