### ISSUE TITLE
Erro validar no point-of-sale

### ISSUE THREAD

**Issue by vanderleiromera** [Trust-Code/odoo-brasil#967]
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/point_of_sale/models/pos_order.py", line 764, in create_from_ui
    pos_order = self._process_order(order)
  File "/opt/odoo/custom/addons/odoo-brasil/br_point_of_sale/models/pos_order.py", line 77, in _process_order
    res = super(PosOrder, self)._process_order(pos_order)
  File "/opt/odoo/odoo-server/addons/point_of_sale/models/pos_order.py", line 120, in _process_order
    order = self.create(self._order_fields(pos_order))
  File "/opt/odoo/custom/addons/odoo-brasil/br_point_of_sale/models/pos_order.py", line 54, in _order_fields
    res.update({'customer_cpf': ui_order['customer_cpf'] or False})
KeyError: 'customer_cpf'

**Comment by vanderleiromera** [comment]
Resolveu ao reiniciar o servidor!

**Comment by vanderleiromera** [comment]
se for só um produto, valida normal, havendo diversos produtos no pos o erro persiste

**Comment by Alexandre-Bernardes** [comment]
estou com o mesmo erro aqui, com um único produto
